version: '{branch}-{build}'
configuration: Release
clone_folder: C:\Textractor
skip_branch_with_pr: false

build: Script

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    fprefix: Textractor
    fprefix2: texthook
    vs_gen: "Visual Studio 16 2019"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    fprefix: Textractor-vs22
    fprefix2: texthook-vs22
    vs_gen: "Visual Studio 17 2022"

before_build:
  - git submodule update --init
  - ps: $date=Get-Date -Format 'yyMMdd'; [Environment]::SetEnvironmentVariable('BUILD_DATE', $date, 'Process')
  - if not "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (
      py -3 -m pip install --user aqtinstall &&
      py -3 -m aqt install-qt windows desktop 5.13.2 win32_msvc2017 --outputdir C:\Qt &&
      py -3 -m aqt install-qt windows desktop 5.13.2 win64_msvc2017_64 --outputdir C:\Qt
    )
  - copy C:\Textractor\languages\qtbase_zh_CN.qm C:\Qt\5.13.2\msvc2017\translations\qtbase_zh_CN.qm
  - copy C:\Textractor\languages\qtbase_zh_CN.qm C:\Qt\5.13.2\msvc2017_64\translations\qtbase_zh_CN.qm
  - copy C:\Textractor\languages\qtbase_pt_BR.qm C:\Qt\5.13.2\msvc2017\translations\qtbase_pt_BR.qm
  - copy C:\Textractor\languages\qtbase_pt_BR.qm C:\Qt\5.13.2\msvc2017_64\translations\qtbase_pt_BR.qm
  - copy C:\Textractor\languages\qtbase_tr.qm C:\Qt\5.13.2\msvc2017\translations\qtbase_tr.qm
  - copy C:\Textractor\languages\qtbase_tr.qm C:\Qt\5.13.2\msvc2017_64\translations\qtbase_tr.qm

build_script:
  - cd C:\
  - mkdir x86 && mkdir x64
  - cd x86
  - cmake -G "%vs_gen%" -A Win32 -DQt5_DIR="C:\Qt\5.13.2\msvc2017\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ..\Textractor
  - cmake --build . --config Release -j 1
  - cd C:\x64
  - cmake -G "%vs_gen%" -A x64 -DQt5_DIR="C:\Qt\5.13.2\msvc2017_64\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="Release" -DVERSION="" ..\Textractor
  - cmake --build . --config Release -j 1

after_build:
  - mkdir C:\textractor-build
  - mkdir C:\textractor-build\x86
  - mkdir C:\textractor-build\x64
  - xcopy C:\Textractor\builds\Release_x86\* C:\textractor-build\x86\ /E /I /Y
  - xcopy C:\Textractor\builds\Release_x64\* C:\textractor-build\x64\ /E /I /Y
  - 7z a %fprefix%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip C:\textractor-build\*
  - appveyor PushArtifact %fprefix%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip
  - mkdir C:\texthook
  - mkdir C:\texthook\x86
  - mkdir C:\texthook\x64
  - copy C:\Textractor\builds\Release_x86\texthook.dll C:\texthook\x86\texthook.dll
  - copy C:\Textractor\builds\Release_x64\texthook.dll C:\texthook\x64\texthook.dll
  - 7z a %fprefix2%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip C:\texthook\*
  - appveyor PushArtifact %fprefix2%-Alpha%APPVEYOR_BUILD_NUMBER%-%BUILD_DATE%.zip

notifications:
- provider: Email
  to:
  - i@chenx221.cyou
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
