// German translations
// Generated by Gemini

NATIVE_LANGUAGE = "German";
ATTACH = u8"An Spiel hängen";
LAUNCH = u8"Spiel starten";
CONFIG = u8"Spiel konfigurieren";
DETACH = u8"Vom Spiel trennen";
FORGET = u8"Spiel vergessen";
RESTART_AS_ADMIN = u8"Als Administrator neu starten";
ADD_HOOK = u8"Hook hinzufügen";
REMOVE_HOOKS = u8"Hook(s) entfernen";
SAVE_HOOKS = u8"Hook(s) speichern";
SEARCH_FOR_HOOKS = u8"Nach Hooks suchen";
SETTINGS = u8"Einstellungen";
EXTENSIONS = u8"Erweiterungen";
SELECT_PROCESS = u8"Prozess auswählen";
ATTACH_INFO = u8R"(Falls der gewünschte Prozess nicht erscheint, versuchen Sie das Programm mit Administratorrechten zu starten.
Sie können auch die Prozess-ID (PID) manuell eingeben.)";
REFRESH = u8"Aktualisieren";
HIDE_INCOMPATIBLE_ARCHITECTURE = u8"Inkompatible Architektur ausblenden";
SELECT_PROCESS_INFO = u8"Wenn Sie den Prozessnamen manuell eingeben, verwenden Sie bitte den absoluten Pfad";
FROM_COMPUTER = u8"Vom Computer auswählen";
PROCESSES = u8"Prozesse (*.exe)";
CODE_INFODUMP = u8R"(Lese-Code (Read Code) eingeben:
R{S|Q|V|M}[null_length<][codepage#]@addr
ODER
Hook-Code eingeben:
H{A|B|W|H|S|Q|V|M}[F][null_length<][N][codepage#][padding+]data_offset[*deref_offset][:split_offset[*deref_offset]]@addr[:module[:func]]
Alle Zahlen außer Codepage/null_length in Hexadezimal.
Standard-Codepage ist 932 (Shift-JIS), kann in den Einstellungen geändert werden.
A/B: Codepage Zeichen Little/Big Endian
W: UTF-16 Zeichen
H: Zwei Hex-Bytes
S/Q/V/M: Codepage/UTF-16/UTF-8/Hex-String
F: Strings als vollständige Textzeilen behandeln
N: Keinen Kontext verwenden
null_length: Länge des Null-Terminators für Strings
padding: Länge der Padding-Daten vor dem String (C-Struct { int64_t size; char string[500]; } benötigt padding = 8)
Negative Werte für data_offset/split_offset beziehen sich auf Register:
-4 für EAX, -8 für ECX, -C für EDX, -10 für EBX, -14 für ESP, -18 für EBP, -1C for ESI, -20 für EDI
-C für RAX, -14 für RBX, -1C für RCX, -24 für RDX, usw. für RSP, RBP, RSI, RDI, R8-R15
* bedeutet Pointer dereferenzieren + deref_offset)";
SAVE_SETTINGS = u8"Einstellungen speichern";
EXTEN_WINDOW_INSTRUCTIONS = u8R"(Rechtsklick auf die Liste, um Erweiterungen hinzuzufügen oder zu entfernen.
Ziehen Sie Erweiterungen innerhalb der Liste, um die Reihenfolge zu ändern.
(Erweiterungen werden von oben nach unten angewendet: Die Reihenfolge ist WICHTIG))";
ADD_EXTENSION = u8"Erweiterung hinzufügen";
REMOVE_EXTENSION = u8"Erweiterung entfernen";
INVALID_EXTENSION = u8"%1 ist eine ungültige Erweiterung";
CONFIRM_EXTENSION_OVERWRITE = u8"Eine andere Version dieser Erweiterung existiert bereits. Möchten Sie diese löschen und überschreiben?";
EXTENSION_WRITE_ERROR = u8"Fehler beim Speichern der Erweiterung";
USE_JP_LOCALE = u8"Japanisches Gebietsschema (Locale) emulieren?";
FAILED_TO_CREATE_CONFIG_FILE = u8"Konfigurationsdatei \"%1\" konnte nicht erstellt werden";
HOOK_SEARCH_UNSTABLE_WARNING = u8"Die Suche nach Hooks ist instabil! Seien Sie darauf vorbereitet, dass das Spiel abstürzen könnte!";
HOOK_SEARCH_STARTING_VIEW_CONSOLE = u8"Hook-Suche wird initialisiert - bitte prüfen Sie die Konsole für weitere Anweisungen";
SEARCH_CJK = u8"Suche nach Chinesisch/Japanisch/Koreanisch";
SEARCH_PATTERN = u8"Suchmuster (Hex-Byte-Array)";
SEARCH_DURATION = u8"Suchdauer (ms)";
SEARCH_MODULE = u8"Innerhalb Modul suchen";
PATTERN_OFFSET = u8"Offset vom Musterstart";
MAX_HOOK_SEARCH_RECORDS = u8"Limit der Suchergebnisse";
MIN_ADDRESS = u8"Minimale Adresse (hex)";
MAX_ADDRESS = u8"Maximale Adresse (hex)";
STRING_OFFSET = u8"String-Offset (hex)";
HOOK_SEARCH_FILTER = u8"Ergebnisse müssen diesem Regex entsprechen";
TEXT = u8"Text";
CODEPAGE = u8"Codepage";
SEARCH_FOR_TEXT = u8"Nach spezifischem Text suchen";
START_HOOK_SEARCH = u8"Hook-Suche starten";
SAVE_SEARCH_RESULTS = u8"Suchergebnisse speichern";
TEXT_FILES = u8"Textdateien (*.txt)";
DOUBLE_CLICK_TO_REMOVE_HOOK = u8"Doppelklicken Sie auf einen Hook, um ihn zu entfernen";
FILTER_REPETITION = u8"Wiederholungen filtern";
AUTO_ATTACH = u8"Automatisch anhängen";
ATTACH_SAVED_ONLY = u8"Auto-Anhängen (nur gespeicherte)";
SHOW_SYSTEM_PROCESSES = u8"Systemprozesse anzeigen";
DEFAULT_CODEPAGE = u8"Standard-Codepage";
FLUSH_DELAY = u8"Flush-Verzögerung";
FLUSH_DELAY_SPACING = u8"Flush-Verzögerung String-Abstand";
MAX_BUFFER_SIZE = u8"Maximale Puffergröße";
MAX_HISTORY_SIZE = u8"Maximale Verlaufshistorie";
LIMIT_STRING_LENGTH = u8"Stringlänge begrenzen (0=Aus)";
CONFIG_JP_LOCALE = u8"Mit japanischer Locale starten";
CONSOLE = L"Konsole";
CLIPBOARD = L"Zwischenablage";
ABOUT = L"Textractor " ARCH L" v" VERSION LR"( entwickelt von Artikash (E-Mail: akashmozumdar@gmail.com)
Projekt-Homepage: https://github.com/Artikash/Textractor
Tutorial-Video: https://github.com/Artikash/Textractor/blob/master/docs/TUTORIAL.md
FAQ: https://github.com/Artikash/Textractor/wiki/FAQ
Bitte kontaktieren Sie Artikash bei Problemen, Funktionswünschen oder Fragen zu Textractor.
Dies ist über die Projekt-Homepage (Abschnitt "Issues") oder per E-Mail möglich.
Quellcode verfügbar unter GPLv3 auf der Projekt-Homepage.
Wenn Ihnen dieses Projekt gefällt, erzählen Sie es bitte weiter! Es ist Zeit, AGTH in den Ruhestand zu schicken :))";
CL_OPTIONS = LR"(Verwendung: Textractor [-p{Prozess-ID|"Prozessname"}]...
Beispiel: Textractor -p4466 -p"Mein Spiel.exe" versucht, Prozesse mit der ID 4466 oder dem Namen "Mein Spiel.exe" zu injizieren.)";
UPDATE_AVAILABLE = L"Update verfügbar: Download unter https://github.com/Artikash/Textractor/releases";
ALREADY_INJECTED = L"Textractor: Bereits injiziert";
NEED_32_BIT = L"Textractor: Architektur-Konflikt: Nur Textractor x86 kann diesen Prozess injizieren";
NEED_64_BIT = L"Textractor: Architektur-Konflikt: Nur Textractor x64 kann diesen Prozess injizieren";
INJECT_FAILED = L"Textractor: Injektion fehlgeschlagen";
LAUNCH_FAILED = L"Textractor: Start fehlgeschlagen";
INVALID_CODE = L"Textractor: Ungültiger Code";
INVALID_CODEPAGE = L"Textractor: Textkonvertierung fehlgeschlagen (ungültige Codepage?)";
PIPE_CONNECTED = u8"Textractor: Pipe verbunden";
INSERTING_HOOK = u8"Textractor: Hook wird eingefügt: %s";
REMOVING_HOOK = u8"Textractor: Hook wird entfernt: %s";
HOOK_FAILED = u8"Textractor: Einfügen des Hooks fehlgeschlagen";
TOO_MANY_HOOKS = u8"Textractor: Zu viele Hooks: Einfügen nicht möglich";
HOOK_SEARCH_STARTING = u8"Textractor: Hook-Suche wird gestartet";
HOOK_SEARCH_INITIALIZING = u8"Textractor: Hook-Suche wird initialisiert (%f%%)";
NOT_ENOUGH_TEXT = u8"Textractor: Nicht genügend Text für eine präzise Suche vorhanden";
HOOK_SEARCH_INITIALIZED = u8"Textractor: Hook-Suche mit %zd Hooks initialisiert";
MAKE_GAME_PROCESS_TEXT = u8"Textractor: Bitte klicken Sie im Spiel umher, um es zu zwingen, in den nächsten %d Sekunden Text zu verarbeiten";
HOOK_SEARCH_FINISHED = u8"Textractor: Hook-Suche beendet, %d Ergebnisse gefunden";
OUT_OF_RECORDS_RETRY = u8"Textractor: Keine Suchdatensätze mehr verfügbar. Bitte versuchen Sie es erneut, falls die Ergebnisse unzureichend sind (Standardlimit wurde erhöht)";
FUNC_MISSING = u8"Textractor: Funktion nicht vorhanden";
MODULE_MISSING = u8"Textractor: Modul nicht vorhanden";
GARBAGE_MEMORY = u8"Textractor: Speicher ändert sich ständig, Auslesen zwecklos";
SEND_ERROR = u8"Textractor: Sende-FEHLER (wahrscheinlich ein instabiler/falscher H-Code)";
READ_ERROR = u8"Textractor: Lese-FEHLER (wahrscheinlich ein falscher R-Code)";
HIJACK_ERROR = u8"Textractor: Hijack-FEHLER";
COULD_NOT_FIND = u8"Textractor: Text konnte nicht gefunden werden";
TRANSLATE_TO = u8"Übersetzen nach";
TRANSLATE_FROM = u8"Übersetzen von";
CONFIGURE_TRANSLATION_SETTINGS = u8"Bitte konfigurieren Sie Quell-/Zielsprache und den API-Schlüssel im externen Übersetzungsprogramm.";
PORT = u8"Port";
TRANSLATE_VERSION = u8"Version";
TRANSLATE_EDITON = u8"Übersetzungs-Edition";
FILTER_GARBAGE = u8"Müllzeichen filtern";
TRANSLATE_SELECTED_THREAD_ONLY = u8"Nur ausgewählten Text-Thread übersetzen";
RATE_LIMIT_ALL_THREADS = u8"Ratenbegrenzung (Rate Limiter) verwenden";
RATE_LIMIT_SELECTED_THREAD = u8"Ratenbegrenzung für ausgewählten Thread";
USE_TRANS_CACHE = u8"Übersetzungs-Cache verwenden";
MAX_TRANSLATIONS_IN_TIMESPAN = u8"Max. Übersetzungsanfragen im Zeitraum";
TIMESPAN = u8"Zeitraum (ms)";
SENTENCE_TOO_LARGE_TO_TRANS = L"Satz zu groß zum Übersetzen";
TOO_MANY_TRANS_REQUESTS = L"Ratenbegrenzung überschritten: Weitere Übersetzungsanfragen abgelehnt";
TRANSLATION_ERROR = L"Fehler bei der Übersetzung";
USE_PREV_SENTENCE_CONTEXT = u8"Vorherigen Satz als Kontext verwenden";
API_KEY = u8"API-Schlüssel";
CHROME_LOCATION = u8"Google Chrome Dateipfad";
START_DEVTOOLS = u8"DevTools starten";
STOP_DEVTOOLS = u8"DevTools stoppen";
HIDE_CHROME = u8"Chrome-Fenster ausblenden";
DEVTOOLS_STATUS = u8"DevTools Status";
AUTO_START = u8"Automatisch starten";
ERROR_START_CHROME = L"Fehler beim Starten von Chrome oder beim Verbindungsaufbau";
EXTRA_WINDOW_INFO = u8R"(Rechtsklick zum Ändern der Einstellungen.
Klicken und ziehen Sie an den Fensterrändern zum Bewegen oder an der unteren rechten Ecke zur Größenänderung.)";
MAX_SENTENCE_SIZE = u8"Maximale Satzgröße";
TOPMOST = u8"Immer im Vordergrund";
DICTIONARY = u8"Wörterbuch";
DICTIONARY_INSTRUCTIONS = u8R"(Diese Datei wird nur für die "Wörterbuch"-Funktion der "Extra Window"-Erweiterung verwendet.
Sie nutzt ein spezielles Format für Textractor und sollte nicht manuell bearbeitet werden.
Suchen Sie online nach einem Wörterbuch in diesem Format (https://github.com/Artikash/Textractor-Dictionaries/releases ist ein guter Ausgangspunkt).
Alternativ können Sie als Programmierer ein Skript schreiben, um ein Wörterbuch aus einem anderen Format mit den untenstehenden Informationen zu konvertieren.
Sobald Sie ein Wörterbuch haben, fahren Sie im "Extra Window" mit der Maus über einen Text, um ihn nachzuschlagen. Sie können durch alle passenden Definitionen scrollen.
Definitionen sind wie folgt formatiert: |TERM|Hola<<ignored|TERM|hola|TERM|Bonjour|TERM|bonjour|DEFINITION|hello|END|
Begriff und Definition können Rich Text (https://doc.qt.io/qt-5/richtext-html-subset.html) enthalten, der korrekt formatiert wird.
Flexionen (Wortbeugungen) sind so formatiert: |ROOT|1<<noun|INFLECTS TO|(\w*)s|NAME| plural|END|
Textractor prüft, ob ein Begriff dem Flexions-Regex entspricht; falls ja, wird rekursiv nach dem Stammwort gesucht.
Das Stammwort wird generiert, indem jede Zahl durch die entsprechende Regex-Capture-Gruppe ersetzt wird (wobei 0 durch den gesamten Treffer ersetzt wird).
Dieser Prozess kann leicht zu Endlosschleifen und/oder Stack-Overflows führen. Es liegt in Ihrer Verantwortung, dies zu vermeiden.
Der Flexions-Regex verwendet die QRegularExpression Unicode-Syntax.
Textractor zeigt das endgültige Stammwort sowie alle verwendeten Flexionen an.
Text in einem Begriff nach << wird bei der Anzeige ignoriert. Dies dient zum Speichern von Wortart-Informationen.
Diese Datei muss in UTF-8 kodiert sein.)";
SHOW_ORIGINAL = u8"Originaltext";
SHOW_ORIGINAL_INFO = u8R"(Originaltext wird nicht angezeigt.
Funktioniert nur, wenn diese Erweiterung direkt nach einer Übersetzungs-Erweiterung verwendet wird.)";
ORIGINAL_AFTER_TRANSLATION = u8"Originaltext nach Übersetzung";
SIZE_LOCK = u8"Größe sperren";
POSITION_LOCK = u8"Position sperren";
CENTERED_TEXT = u8"Zentrierter Text";
AUTO_RESIZE_WINDOW_HEIGHT = u8"Fensterhöhe automatisch anpassen";
CLICK_THROUGH = u8"Durchklicken\tAlt+X";
HIDE_MOUSEOVER = u8"Bei Mouseover ausblenden";
HIDE_TEXT = u8"Text verbergen/anzeigen\tAlt+T";
OPACITY = u8"Deckkraft";
BG_COLOR = u8"Hintergrundfarbe";
TEXT_COLOR = u8"Textfarbe";
TEXT_OUTLINE = u8"Textumrandung";
OUTLINE_COLOR = u8"Umrandungsfarbe";
OUTLINE_SIZE = u8"Umrandungsgröße";
OUTLINE_SIZE_INFO = u8"Größe in Pixeln (empfohlen unter 20% der Schriftgröße)";
FONT = u8"Schriftart";
TIMER_HIDE_TEXT = u8"Timer: Text ausblenden";
TEXT_TIMEOUT = u8"Zeitlimit (ms, 0=deaktiviert)";
TEXT_TIMEOUT_ADD_PER_CHAR = u8"Zusätzliches Zeitlimit pro Zeichen (ms)";
LUA_INTRO = u8R"(--[[
ProcessSentence wird jedes Mal aufgerufen, wenn Textractor einen Satz erhält.

Parameter sentence: Von Textractor empfangener Satz (UTF-8).
Parameter sentenceInfo: Tabelle mit verschiedenen Informationen zum Satz.

Wenn Sie einen String zurückgeben, wird der Satz durch diesen String ersetzt.
Wenn Sie nil zurückgeben, bleibt der Satz unverändert.

Diese Erweiterung verwendet mehrere Kopien des Lua-Interpreters für Threadsicherheit.
Änderungen an globalen Variablen in ProcessSentence bleiben garantiert nicht dauerhaft bestehen.

Eigenschaften in sentenceInfo:
"current select": 0, außer der Satz befindet sich im aktuell vom Benutzer ausgewählten Text-Thread.
"process id": Prozess-ID, von der der Satz stammt. 0 für Konsole und Zwischenablage.
"text number": Nummer des aktuellen Text-Threads. Wird fortlaufend hochgezählt. 0 für Konsole, 1 für Zwischenablage.
--]]
function ProcessSentence(sentence, sentenceInfo)
  --Ihr Code hier...
end)";
LOAD_SCRIPT = u8"Skript laden";
LUA_ERROR = L"Lua-Fehler: %s";
REGEX_FILTER = u8"Regex-Filter";
INVALID_REGEX = u8"Ungültiger Regex";
CURRENT_FILTER = u8"Aktueller Filter: %1";
REPLACER_INSTRUCTIONS = LR"(Diese Datei hat nur Auswirkungen, wenn die "Replacer"-Erweiterung verwendet wird.
Ersetzungsbefehle müssen wie folgt formatiert sein:
|ORIG|Originaltext|BECOMES|Ersetzungstext|END|
Sämtlicher Text in dieser Datei außerhalb eines Ersetzungsbefehls wird ignoriert.
Ein Zirkumflex (^) dient als Platzhalter für ein beliebiges einzelnes Zeichen.
Leerzeichen im Originaltext werden ignoriert, der Ersetzungstext kann jedoch Leerzeichen, Zeilenumbrüche usw. enthalten.
Diese Datei muss in Unicode (UTF-16 Little Endian) kodiert sein.)";
REGEX_REPLACER_INSTRUCTIONS = LR"(Diese Datei hat nur Auswirkungen, wenn die "Regex Replacer"-Erweiterung verwendet wird.
Ersetzungsbefehle müssen wie folgt formatiert sein:
|REGEX|Regulärer_Ausdruck|BECOMES|Ersetzungstext|MODIFIER|Modifier|END|
Der Ersetzungstext kann auf Capture-Gruppen mit einem $ gefolgt von der Nummer verweisen (z. B. $1 für die erste Gruppe).
Modifier können Folgendes enthalten:
"g" die Ersetzung erfolgt global.
"i" die Ersetzung ignoriert Groß-/Kleinschreibung.
Falls leer, erfolgt die Ersetzung nur beim ersten Treffer und beachtet die Groß-/Kleinschreibung.
Sämtlicher Text in dieser Datei außerhalb eines Ersetzungsbefehls wird ignoriert.
Diese Datei muss in Unicode (UTF-16 Little Endian) kodiert sein.
Reguläre Ausdrücke lernen, erstellen & testen: https://regexr.com/)";
THREAD_LINKER = u8"Thread-Linker";
LINK = u8"Verknüpfen";
UNLINK = u8"Verknüpfung aufheben";
THREAD_LINK_FROM = u8"Quell-Thread-Nummer";
THREAD_LINK_TO = u8"Ziel-Thread-Nummer";
HEXADECIMAL = u8"Hexadezimal";
LANGUAGE_SETTING = u8"Sprache (erfordert Neustart)";
LANGUAGE_RESTART_NOTICE = u8"Sprachänderungen werden nach einem Neustart von Textractor wirksam";
CHECK_UPDATE = u8"Beim Start nach Texthook-Updates suchen";
ORIGINAL_FONT = u8"OriginalSchriftart";
TRANSLATED_FONT = u8"ÜbersetzteSchriftart";
WINHTTP_TIMEOUT = L"Zeitüberschreitung der Anforderung";
WINHTTP_NAME_NOT_RESOLVED = L"DNS-Auflösung fehlgeschlagen";
WINHTTP_CANNOT_CONNECT = L"Verbindung zum Server nicht möglich";
WINHTTP_CONNECTION_ERROR = L"Verbindung abgebrochen";
WINHTTP_SECURE_FAILURE = L"TLS/SSL-Handshake fehlgeschlagen";
WINHTTP_INVALID_SERVER_RESPONSE = L"Ungültige Serverantwort";
WINHTTP_OPERATION_CANCELLED = L"Anforderung abgebrochen";
UNKNOWN_ERROR = L"Unbekannter Fehler";
CHECKING_UPDATE = L"Suche nach Updates...";
OPEN_TEXTHOOK_FAILED = L"texthook.dll konnte nicht geöffnet werden.";
CHECK_UPDATE_FAILED = L"Update-Prüfung fehlgeschlagen: %s";
CHECK_UPDATE_FAILED_CODE = L"Update-Prüfung fehlgeschlagen: %s (Code=%u).";
CHECK_UPDATE_FAILED_HTTP = L"Update-Prüfung fehlgeschlagen: HTTP-Status %u.";
CHECK_UPDATE_FAILED_EMPTY_RESPONSE = L"Update-Prüfung fehlgeschlagen: Leere Serverantwort.";
CHECK_UPDATE_FAILED_MALFORMED_RESPONSE = L"Update-Prüfung fehlgeschlagen: Fehlerhafte JSON-Antwort.";
CHECK_UPDATE_FAILED_UNKNOWN = L"Update-Prüfung fehlgeschlagen: Server gab einen unbekannten Fehler zurück.";
CHECK_UPDATE_FAILED_UNEXPECTED_RESPONSE = L"Unerwartete Antwort vom Update-Server.\nBesuchen Sie den Server im Browser, um das Problem zu prüfen: https://api.iloli.one";
TEXTHOOK_UPDATE_AVAILABLE = L"Texthook-Update gefunden!\nAktuell: %s, Neu: %s\nDownload: %s";
TEXTHOOK_IS_LATEST = L"Texthook ist auf dem neuesten Stand.";
TENCENT_AUTH_PROMPT = L"Bitte geben Sie SecretId|SecretKey für Tencent Cloud Translation im Feld für den API-Schlüssel ein";
LINGOCLOUD_AUTH_PROMPT = L"Bitte geben Sie das API-Token für Lingocloud Translation im Feld für den API-Schlüssel ein";
TRANSLATION_NO_TRANSLATION_FOUND = L"Keine Übersetzung in der Antwort gefunden";
TRANSLATION_JSON_PARSE_ERROR = L"JSON-Parse-Fehler";
TRANSLATION_KEY_ERROR = L"Schlüssel-Fehler in der Übersetzungstabelle";
TRANSLATION_EXCEPTION_OCCURRED = L"Ausnahme aufgetreten";
TRANSLATION_UNKNOWN_ERROR = L"Unbekannter Fehler während der Übersetzung";
TRANSLATION_EMPTY_RESPONSE = L"Leere Antwort von der Übersetzungs-API";
TRANSLATION_RESPONSE_PARSE_DATA_EMPTY = L"Leere Datenzeile nach dem Parsen der Antwort";
TRANSLATION_INVALID_JSON_FORMAT = L"Ungültiges JSON-Antwortformat";
TRANSLATION_UNEXPECTED_STRUCTURE = L"Unerwartete Antwortstruktur";
TRANSLATION_INVALID_DATA_STRUCTURE = L"Ungültige Übersetzungsdatenstruktur";
TRANSLATION_EMPTY_ARRAY = L"Leeres Übersetzungs-Array";
TRANSLATION_INVALID_ENTRY = L"Ungültiger Übersetzungseintrag";
TRANSLATION_EMPTY_SEGMENTS = L"Leere Übersetzungssegmente";
TRANSLATION_NO_TEXT_IN_SEGMENTS = L"Kein Übersetzungstext in den Segmenten gefunden";
TRANSLATION_RETRY_LIMIT_REACHED = L"Wiederholungslimit erreicht";
ALIYUN_CSRF_TOKEN_NOT_FOUND = L"CSRF-Token nicht in der Antwort gefunden";
ALIYUN_INVALID_API_KEY_FORMAT = L"Ungültiges API-Key-Format. Erwartet: accessKeyId|accessKeySecret";
ALIYUN_API_ERROR = L"Aliyun API-Fehler";
BING_TOKEN_RESPONSE_EMPTY = L"Token-Antwort ist leer";
BING_COULD_NOT_ACQUIRE_TOKEN = L"Token konnte nicht abgerufen werden";
BING_TOKEN_NOT_FOUND = L"Token nicht gefunden";
BAIDU_MD5_SIGNATURE_FAILED = L"MD5-Signaturgenerierung fehlgeschlagen.";