// Japanese translations
// Generated by Gemini

NATIVE_LANGUAGE = "Japanese";
ATTACH = u8"ゲームに接続";
LAUNCH = u8"ゲームを起動";
CONFIG = u8"ゲーム設定";
DETACH = u8"ゲームから切断";
FORGET = u8"このゲームを削除";
RESTART_AS_ADMIN = u8"管理者として再起動";
ADD_HOOK = u8"フックを追加";
REMOVE_HOOKS = u8"フックを削除";
SAVE_HOOKS = u8"フックを保存";
SEARCH_FOR_HOOKS = u8"フックを検索";
SETTINGS = u8"設定";
EXTENSIONS = u8"拡張機能";
SELECT_PROCESS = u8"プロセスを選択";
ATTACH_INFO = u8R"(アタッチしたいプロセスが表示されない場合は、管理者権限で実行してください。
プロセスIDを直接入力することも可能です。)";
REFRESH = u8"更新";
HIDE_INCOMPATIBLE_ARCHITECTURE = u8"互換性のないアーキテクチャを非表示";
SELECT_PROCESS_INFO = u8"プロセス名を直接入力する場合は、絶対パスを使用してください。";
FROM_COMPUTER = u8"コンピュータから選択";
PROCESSES = u8"実行ファイル (*.exe)";
CODE_INFODUMP = u8R"(読み取りコードを入力
R{S|Q|V|M}[null_length<][codepage#]@addr
または
フックコードを入力
H{A|B|W|H|S|Q|V|M}[F][null_length<][N][codepage#][padding+]data_offset[*deref_offset][:split_offset[*deref_offset]]@addr[:module[:func]]
codepage/null_length以外の数値はすべて16進数です。
デフォルトのコードページは932 (Shift-JIS) です（設定で変更可能）。
A/B: コードページ文字 リトル/ビッグエンディアン
W: UTF-16 文字
H: 2バイトの16進数
S/Q/V/M: コードページ/UTF-16/UTF-8/16進数文字列
F: 文字列をテキストの全行として処理
N: コンテキストを使用しない
null_length: 文字列に使用されるヌル終端の長さ
padding: 文字列前のパディング長 (例: C構造体 { int64_t size; char string[500]; } は padding = 8)
負の値はレジスタを指します:
-4:EAX, -8:ECX, -C:EDX, -10:EBX, -14:ESP, -18:EBP, -1C:ESI, -20:EDI
-C:RAX, -14:RBX, -1C:RCX, -24:RDX など
* はポインタのデリファレンスを意味します)";
SAVE_SETTINGS = u8"設定を保存";
EXTEN_WINDOW_INSTRUCTIONS = u8R"(リストを右クリックして拡張機能を追加・削除します。
ドラッグ＆ドロップで実行順序を入れ替えられます。
（拡張機能は上から下に順次適用されるため、順序は非常に重要です）)";
ADD_EXTENSION = u8"拡張機能を追加";
REMOVE_EXTENSION = u8"拡張機能を削除";
INVALID_EXTENSION = u8"%1 は無効な拡張機能です";
CONFIRM_EXTENSION_OVERWRITE = u8"同名の拡張機能が既に存在します。上書きしますか？";
EXTENSION_WRITE_ERROR = u8"拡張機能の保存に失敗しました";
USE_JP_LOCALE = u8"日本ロケールをエミュレートしますか？";
FAILED_TO_CREATE_CONFIG_FILE = u8"設定ファイル \"%1\" の作成に失敗しました";
HOOK_SEARCH_UNSTABLE_WARNING = u8"フック検索は不安定です！ゲームがクラッシュする可能性があります！";
HOOK_SEARCH_STARTING_VIEW_CONSOLE = u8"フック検索を初期化中 - コンソールの指示を確認してください";
SEARCH_CJK = u8"中国語・日本語・韓国語の文字を検索";
SEARCH_PATTERN = u8"検索パターン (hex byte array)";
SEARCH_DURATION = u8"検索時間 (ms)";
SEARCH_MODULE = u8"モジュール内を検索";
PATTERN_OFFSET = u8"パターン開始位置からのオフセット";
MAX_HOOK_SEARCH_RECORDS = u8"検索結果の上限";
MIN_ADDRESS = u8"最小アドレス (hex)";
MAX_ADDRESS = u8"最大アドレス (hex)";
STRING_OFFSET = u8"文字列オフセット (hex)";
HOOK_SEARCH_FILTER = u8"正規表現に一致する結果のみ表示";
TEXT = u8"テキスト";
CODEPAGE = u8"コードページ";
SEARCH_FOR_TEXT = u8"特定のテキストを検索";
START_HOOK_SEARCH = u8"フック検索を開始";
SAVE_SEARCH_RESULTS = u8"検索結果を保存";
TEXT_FILES = u8"テキストファイル (*.txt)";
DOUBLE_CLICK_TO_REMOVE_HOOK = u8"ダブルクリックでフックを削除";
FILTER_REPETITION = u8"重複を除去";
AUTO_ATTACH = u8"自動接続";
ATTACH_SAVED_ONLY = u8"自動アタッチ (保存済みのみ)";
SHOW_SYSTEM_PROCESSES = u8"システムプロセスを表示";
DEFAULT_CODEPAGE = u8"デフォルトコードページ";
FLUSH_DELAY = u8"フラッシュ遅延";
FLUSH_DELAY_SPACING = u8"フラッシュ遅延（文字間隔）";
MAX_BUFFER_SIZE = u8"最大バッファサイズ";
MAX_HISTORY_SIZE = u8"最大履歴サイズ";
LIMIT_STRING_LENGTH = u8"文字列長を制限 (0=無効)";
CONFIG_JP_LOCALE = u8"日本ロケールで起動";
CONSOLE = L"コンソール";
CLIPBOARD = L"クリップボード";
ABOUT = L"Textractor " ARCH L" v" VERSION LR"( 作成者: Artikash (email: akashmozumdar@gmail.com)
プロジェクトページ: https://github.com/Artikash/Textractor
チュートリアル動画: https://github.com/Artikash/Textractor/blob/master/docs/TUTORIAL.md
FAQ: https://github.com/Artikash/Textractor/wiki/FAQ
ソースコードはGPLv3ライセンスで公開されています。
このプロジェクトを気に入っていただけたら、ぜひ周りに広めてください！)";
UPDATE_AVAILABLE = L"アップデートがあります：https://github.com/Artikash/Textractor/releases からダウンロードしてください";
ALREADY_INJECTED = L"Textractor: 既にインジェクトされています";
NEED_32_BIT = L"Textractor: アーキテクチャ不一致: x86版を使用してください";
NEED_64_BIT = L"Textractor: アーキテクチャ不一致: x64版を使用してください";
INJECT_FAILED = L"Textractor: インジェクトに失敗しました";
LAUNCH_FAILED = L"Textractor: 起動に失敗しました";
INVALID_CODE = L"Textractor: 無効なコード";
INVALID_CODEPAGE = L"Textractor: テキスト変換失敗 (無効なコードページ？)";
PIPE_CONNECTED = u8"Textractor: パイプが接続されました";
INSERTING_HOOK = u8"Textractor: フックを挿入中: %s";
REMOVING_HOOK = u8"Textractor: フックを削除中: %s";
HOOK_FAILED = u8"Textractor: フックの挿入に失敗しました";
TOO_MANY_HOOKS = u8"Textractor: フック数が上限に達しました";
HOOK_SEARCH_STARTING = u8"Textractor: フック検索を開始します";
HOOK_SEARCH_INITIALIZING = u8"Textractor: フック検索を初期化中 (%f%%)";
NOT_ENOUGH_TEXT = u8"Textractor: 検索に必要なテキストが不足しています";
HOOK_SEARCH_INITIALIZED = u8"Textractor: %zd 個のフックで検索を初期化しました";
MAKE_GAME_PROCESS_TEXT = u8"Textractor: 次の %d 秒間にゲーム内でテキストを進めてください";
HOOK_SEARCH_FINISHED = u8"Textractor: フック検索終了。%d 件の結果が見つかりました";
OUT_OF_RECORDS_RETRY = u8"Textractor: 検索レコード不足です。必要に応じて再試行してください";
FUNC_MISSING = u8"Textractor: 関数が見つかりません";
MODULE_MISSING = u8"Textractor: モジュールが見つかりません";
GARBAGE_MEMORY = u8"Textractor: メモリが常に変化しているため読み取れません";
SEND_ERROR = u8"Textractor: 送信エラー (Hコードが正しくない可能性があります)";
READ_ERROR = u8"Textractor: 読み取りエラー (Rコードが正しくない可能性があります)";
HIJACK_ERROR = u8"Textractor: ハイジャックエラー";
COULD_NOT_FIND = u8"Textractor: テキストが見つかりませんでした";
TRANSLATE_TO = u8"翻訳先";
TRANSLATE_FROM = u8"翻訳元";
CONFIGURE_TRANSLATION_SETTINGS = u8"外部翻訳プログラムで言語とAPIキーを設定してください。";
PORT = u8"ポート";
TRANSLATE_VERSION = u8"バージョン";
TRANSLATE_EDITON = u8"翻訳版";
FILTER_GARBAGE = u8"不要な文字をフィルタ";
TRANSLATE_SELECTED_THREAD_ONLY = u8"選択したスレッドのみ翻訳";
RATE_LIMIT_ALL_THREADS = u8"レートリミッターを使用";
RATE_LIMIT_SELECTED_THREAD = u8"選択したスレッドをレート制限";
USE_TRANS_CACHE = u8"翻訳キャッシュを使用";
MAX_TRANSLATIONS_IN_TIMESPAN = u8"時間枠内の最大リクエスト数";
TIMESPAN = u8"時間枠 (ms)";
SENTENCE_TOO_LARGE_TO_TRANS = L"文章が長すぎて翻訳できません";
TOO_MANY_TRANS_REQUESTS = L"レート制限を超えました：リクエストを拒否しました";
TRANSLATION_ERROR = L"翻訳中にエラーが発生しました";
USE_PREV_SENTENCE_CONTEXT = u8"前の文をコンテキストとして使用";
API_KEY = u8"APIキー";
CHROME_LOCATION = u8"Google Chromeの場所";
START_DEVTOOLS = u8"DevToolsを開始";
STOP_DEVTOOLS = u8"DevToolsを停止";
HIDE_CHROME = u8"Chromeウィンドウを隠す";
DEVTOOLS_STATUS = u8"DevToolsステータス";
AUTO_START = u8"自動開始";
ERROR_START_CHROME = L"Chromeの起動または接続に失敗しました";
EXTRA_WINDOW_INFO = u8R"(右クリックで設定変更
ウィンドウの端をドラッグして移動、右下をドラッグしてリサイズ)";
MAX_SENTENCE_SIZE = u8"最大文章サイズ";
TOPMOST = u8"常に最前面に表示";
DICTIONARY = u8"辞書";
DICTIONARY_INSTRUCTIONS = u8R"(このファイルはExtra Window拡張機能の「辞書」機能でのみ使用されます。
Textractor独自の形式であり、手動での作成は推奨されません。
辞書ファイルはオンライン（https://github.com/Artikash/Textractor-Dictionaries/releasesなど）で探してください。
プログラマーであれば、以下の情報を元に他の形式から変換スクリプトを書くことが可能です。
辞書を設定後、Extra Window上でテキストにホバーすると定義が表示されます。
定義形式：|TERM|Hola<<ignored|TERM|hola|TERM|Bonjour|TERM|bonjour|DEFINITION|hello|END|
項目の定義にはリッチテキスト (HTML) が使用可能です。
屈折形式：|ROOT|1<<noun|INFLECTS TO|(\w*)s|NAME| plural|END|
Textractorは正規表現に一致する場合、再帰的にルート語を検索します。
このプロセスは無限ループを招く可能性があるため、注意して作成してください。
ファイルはUTF-8でエンコードされている必要があります。)";
SHOW_ORIGINAL = u8"原文を表示";
SHOW_ORIGINAL_INFO = u8R"(原文は表示されません
翻訳拡張機能の直後にこの拡張機能を使用する場合のみ有効です)";
ORIGINAL_AFTER_TRANSLATION = u8"翻訳後に原文を表示";
SIZE_LOCK = u8"サイズを固定";
POSITION_LOCK = u8"位置を固定";
CENTERED_TEXT = u8"テキストを中央揃え";
AUTO_RESIZE_WINDOW_HEIGHT = u8"ウィンドウの高さを自動調整";
CLICK_THROUGH = u8"クリックスルー\tAlt+X";
HIDE_MOUSEOVER = u8"マウスホバー時に隠す";
HIDE_TEXT = u8"テキストを表示/非表示\tAlt+T";
OPACITY = u8"不透明度";
BG_COLOR = u8"背景色";
TEXT_COLOR = u8"文字色";
TEXT_OUTLINE = u8"文字の縁取り";
OUTLINE_COLOR = u8"縁取りの色";
OUTLINE_SIZE = u8"縁取りのサイズ";
OUTLINE_SIZE_INFO = u8"ピクセル単位 (フォントサイズの20%以下を推奨)";
FONT = u8"フォント";
TIMER_HIDE_TEXT = u8"テキストを自動で隠す";
TEXT_TIMEOUT = u8"タイムアウト (ms, 0=無効)";
TEXT_TIMEOUT_ADD_PER_CHAR = u8"1文字あたりの追加タイムアウト (ms)";
LUA_INTRO = u8R"(--[[
ProcessSentenceは、Textractorがテキストを受信するたびに呼び出されます。

引数 sentence: 受信したテキスト (UTF-8)
引数 sentenceInfo: テキストに関する情報のテーブル

文字列を返すと、その文字列がテキストとして表示されます。
nilを返すと、テキストは変更されません。

Properties in sentenceInfo:
"current select": ユーザーが現在選択しているスレッドの場合は1、それ以外は0。
"process id": プロセスID。コンソールやクリップボードは0。
"text number": テキストスレッドの番号。
--]]
function ProcessSentence(sentence, sentenceInfo)
  -- ここにコードを記述...
end)";
LOAD_SCRIPT = u8"スクリプトを読み込む";
LUA_ERROR = L"Luaエラー: %s";
REGEX_FILTER = u8"正規表現フィルタ";
INVALID_REGEX = u8"無効な正規表現";
CURRENT_FILTER = u8"現在のフィルタ: %1";
REPLACER_INSTRUCTIONS = LR"(Replacer拡張機能で使用されるファイルです。
置換コマンドの形式:
|ORIG|置換前|BECOMES|置換後|END|
^ は任意の1文字に一致するワイルドカードとして機能します。
UTF-16 Little Endianで保存してください。)";
REGEX_REPLACER_INSTRUCTIONS = LR"(Regex Replacer拡張機能で使用されるファイルです。
置換コマンドの形式:
|REGEX|正規表現|BECOMES|置換後|MODIFIER|修飾子|END|
修飾子: "g" (グローバル), "i" (大文字小文字を区別しない)
UTF-16 Little Endianで保存してください。)";
THREAD_LINKER = u8"スレッドリンカー";
LINK = u8"リンク";
UNLINK = u8"リンク解除";
THREAD_LINK_FROM = u8"リンク元スレッド番号";
THREAD_LINK_TO = u8"リンク先スレッド番号";
HEXADECIMAL = u8"16進数";
LANGUAGE_SETTING = u8"言語 (再起動が必要)";
LANGUAGE_RESTART_NOTICE = u8"言語設定は再起動後に有効になります";
CHECK_UPDATE = u8"起動時にTexthookの更新を確認";
ORIGINAL_FONT = u8"原文フォント";
TRANSLATED_FONT = u8"翻訳フォント";
WINHTTP_TIMEOUT = L"リクエストがタイムアウトしました";
WINHTTP_NAME_NOT_RESOLVED = L"DNS解決に失敗しました";
WINHTTP_CANNOT_CONNECT = L"サーバーに接続できません";
WINHTTP_CONNECTION_ERROR = L"接続が断絶されました";
WINHTTP_SECURE_FAILURE = L"TLS/SSLハンドシェイク失敗";
WINHTTP_INVALID_SERVER_RESPONSE = L"無効なサーバーレスポンス";
WINHTTP_OPERATION_CANCELLED = L"リクエストがキャンセルされました";
UNKNOWN_ERROR = L"未知のエラー";
CHECKING_UPDATE = L"更新を確認中...";
OPEN_TEXTHOOK_FAILED = L"texthook.dllの読み込みに失敗しました。";
CHECK_UPDATE_FAILED = L"更新確認失敗: %s";
CHECK_UPDATE_FAILED_CODE = L"更新確認失敗: %s (code=%u)";
CHECK_UPDATE_FAILED_HTTP = L"更新確認失敗: HTTPステータス %u";
CHECK_UPDATE_FAILED_EMPTY_RESPONSE = L"更新確認失敗: レスポンスが空です";
CHECK_UPDATE_FAILED_MALFORMED_RESPONSE = L"更新確認失敗: JSON形式が不正です";
CHECK_UPDATE_FAILED_UNKNOWN = L"更新確認失敗: 未知のエラーが発生しました";
CHECK_UPDATE_FAILED_UNEXPECTED_RESPONSE = L"アップデートサーバーから予期しない応答がありました。\nブラウザで直接確認してください: https://api.iloli.one";
TEXTHOOK_UPDATE_AVAILABLE = L"Texthookの更新が見つかりました！\n現在: %s, 新規: %s\nダウンロード: %s";
TEXTHOOK_IS_LATEST = L"Texthookは最新です。";
TENCENT_AUTH_PROMPT = L"APIキー欄に SecretId|SecretKey を入力してください";
LINGOCLOUD_AUTH_PROMPT = L"APIキー欄に APIトークンを入力してください";
TRANSLATION_NO_TRANSLATION_FOUND = L"レスポンスに翻訳が見つかりませんでした";
TRANSLATION_JSON_PARSE_ERROR = L"JSON解析エラー";
TRANSLATION_KEY_ERROR = L"翻訳マップのキーエラー";
TRANSLATION_EXCEPTION_OCCURRED = L"例外が発生しました";
TRANSLATION_UNKNOWN_ERROR = L"翻訳中に未知のエラーが発生しました";
TRANSLATION_EMPTY_RESPONSE = L"翻訳APIからのレスポンスが空です";
TRANSLATION_RESPONSE_PARSE_DATA_EMPTY = L"応答解析後のデータが空です";
TRANSLATION_INVALID_JSON_FORMAT = L"無効なJSONレスポンス形式";
TRANSLATION_UNEXPECTED_STRUCTURE = L"予期しないレスポンス構造";
TRANSLATION_INVALID_DATA_STRUCTURE = L"翻訳データの構造が無効です";
TRANSLATION_EMPTY_ARRAY = L"翻訳配列が空です";
TRANSLATION_INVALID_ENTRY = L"無効な翻訳エントリです";
TRANSLATION_EMPTY_SEGMENTS = L"翻訳セグメントが空です";
TRANSLATION_NO_TEXT_IN_SEGMENTS = L"セグメント内に翻訳テキストが見つかりません";
TRANSLATION_RETRY_LIMIT_REACHED = L"リトライ上限に達しました";
ALIYUN_CSRF_TOKEN_NOT_FOUND = L"レスポンスにCSRFトークンが見つかりません";
ALIYUN_INVALID_API_KEY_FORMAT = L"APIキー形式が無効です。期待値: accessKeyId|accessKeySecret";
ALIYUN_API_ERROR = L"Aliyun APIエラー";
BING_TOKEN_RESPONSE_EMPTY = L"トークンレスポンスが空です";
BING_COULD_NOT_ACQUIRE_TOKEN = L"トークンを取得できませんでした";
BING_TOKEN_NOT_FOUND = L"トークンが見つかりません";
BAIDU_MD5_SIGNATURE_FAILED = L"MD5シグネチャ生成に失敗しました。";