// Chinese (Traditional) translations
// Generated by Gemini

NATIVE_LANGUAGE = "Chinese (Traditional)";
ATTACH = u8"附加到遊戲";
LAUNCH = u8"啟動遊戲";
CONFIG = u8"配置遊戲";
DETACH = u8"與遊戲分離";
FORGET = u8"清除遊戲配置";
RESTART_AS_ADMIN = u8"以管理員權限重新啟動";
ADD_HOOK = u8"新增 Hook";
REMOVE_HOOKS = u8"移除 Hook";
SAVE_HOOKS = u8"儲存 Hook";
SEARCH_FOR_HOOKS = u8"搜尋 Hook";
SETTINGS = u8"設定";
EXTENSIONS = u8"擴充功能";
SELECT_PROCESS = u8"選擇程序";
ATTACH_INFO = u8R"(如果沒看到想要附加的程序，請嘗試以管理員權限執行 Textractor
也可以手動輸入程序 ID (PID))";
REFRESH = u8"重新整理";
HIDE_INCOMPATIBLE_ARCHITECTURE = u8"隱藏架構不相容的程序";
SELECT_PROCESS_INFO = u8"如果手動輸入遊戲檔名，請使用絕對路徑";
FROM_COMPUTER = u8"從檔案瀏覽器中選擇";
PROCESSES = u8"執行檔 (*.exe)";
CODE_INFODUMP = u8R"(輸入 R-code
R{S|Q|V|M}[null_length<][codepage#]@addr
或
輸入 H-code
H{A|B|W|H|S|Q|V|M}[F][null_length<][N][codepage#][padding+]data_offset[*deref_offset][:split_offset[*deref_offset]]@addr[:module[:func]]
除 codepage/null_length 外，所有數字均為十六進位。
預設代碼頁為 932 (Shift-JIS)，可在設定中修改。
A/B: 小端/大端代碼頁字元
W: UTF-16 字元
H: 兩個十六進位位元組
S/Q/V/M: 代碼頁/UTF-16/UTF-8/十六進位字串
F: 將字串視為完整行
N: 不使用上下文 (Context)
null_length: 字串使用的空終止符長度
padding: 字串前的填充數據長度 (例如 C 結構 { int64_t size; char string[500]; } 需要 padding = 8)
data_offset/split_offset 的負值代表暫存器：
-4:EAX, -8:ECX, -C:EDX, -10:EBX, -14:ESP, -18:EBP, -1C:ESI, -20:EDI
-C:RAX, -14:RBX, -1C:RCX, -24:RDX, 其餘 RSP, RBP, RSI, RDI, R8-R15 依此類推
* 表示對指標+deref_offset進行取值 (Dereference))";
SAVE_SETTINGS = u8"儲存設定";
EXTEN_WINDOW_INSTRUCTIONS = u8R"(在清單中按右鍵以新增或移除擴充功能
在清單中拖曳擴充功能可以調整執行順序，擴充功能會由上而下依序執行
排在下方的擴充功能只能接收到經由上方擴充功能處理過後的文字)";
ADD_EXTENSION = u8"新增擴充功能";
REMOVE_EXTENSION = u8"移除擴充功能";
INVALID_EXTENSION = u8"%1 是無效的擴充功能";
CONFIRM_EXTENSION_OVERWRITE = u8"此擴充功能的另一個版本已啟用，是否刪除並覆蓋它？";
EXTENSION_WRITE_ERROR = u8"儲存擴充功能失敗";
USE_JP_LOCALE = u8"模擬日本地區設定？";
FAILED_TO_CREATE_CONFIG_FILE = u8"無法建立設定檔 \"%1\"";
HOOK_SEARCH_UNSTABLE_WARNING = u8"搜尋 Hook 的功能不穩定！可能會導致遊戲崩潰！";
HOOK_SEARCH_STARTING_VIEW_CONSOLE = u8"正在初始化 Hook 搜尋 - 請查看主控台以獲取更多提示";
SEARCH_CJK = u8"搜尋中/日/韓文";
SEARCH_PATTERN = u8"搜尋特徵碼 (Hex Byte Array)";
SEARCH_DURATION = u8"搜尋持續時間 (ms)";
SEARCH_MODULE = u8"搜尋指定模組";
PATTERN_OFFSET = u8"相對於特徵碼起始位置的偏移值";
MAX_HOOK_SEARCH_RECORDS = u8"搜尋結果上限";
MIN_ADDRESS = u8"起始位址 (Hex)";
MAX_ADDRESS = u8"結束位址 (Hex)";
STRING_OFFSET = u8"字串偏移值 (Hex)";
HOOK_SEARCH_FILTER = u8"結果必須符合此正規表達式 (Regex)";
TEXT = u8"文字";
CODEPAGE = u8"代碼頁";
SEARCH_FOR_TEXT = u8"搜尋特定文字";
START_HOOK_SEARCH = u8"開始搜尋 Hook";
SAVE_SEARCH_RESULTS = u8"儲存搜尋結果";
TEXT_FILES = u8"文字檔案 (*.txt)";
DOUBLE_CLICK_TO_REMOVE_HOOK = u8"按兩下移除不需要的 Hook";
FILTER_REPETITION = u8"過濾重複文字";
AUTO_ATTACH = u8"自動附加";
ATTACH_SAVED_ONLY = u8"自動附加 (僅限已儲存配置的遊戲)";
SHOW_SYSTEM_PROCESSES = u8"顯示系統程序";
DEFAULT_CODEPAGE = u8"預設代碼頁";
FLUSH_DELAY = u8"刷新延遲";
FLUSH_DELAY_SPACING = u8"刷新延遲字串間距";
MAX_BUFFER_SIZE = u8"最大緩衝區長度";
MAX_HISTORY_SIZE = u8"最大歷史紀錄數量";
LIMIT_STRING_LENGTH = u8"限制字串長度 (0=關閉)";
CONFIG_JP_LOCALE = u8"以日本地區設定啟動遊戲";
CONSOLE = L"主控台";
CLIPBOARD = L"剪貼簿";
ABOUT = L"Textractor " ARCH L" v" VERSION LR"( 作者: Artikash (Email: akashmozumdar@gmail.com)
專案首頁: https://github.com/Artikash/Textractor
教學影片: https://github.com/Artikash/Textractor/blob/master/docs/TUTORIAL.md
常見問題 (FAQ): https://github.com/Artikash/Textractor/wiki/FAQ
如有任何關於 Textractor 的困難、功能請求或問題，請聯絡我
可以透過專案首頁 (Issues 頁面) 或電子郵件聯絡
專案首頁提供基於 GPLv3 協議的原始碼
如果你喜歡這個專案，請分享給所有人！是時候讓 AGTH 退休了 :) )";
UPDATE_AVAILABLE = L"有可用的更新：請從 https://github.com/Artikash/Textractor/releases 下載";
ALREADY_INJECTED = L"Textractor: 已經注入";
NEED_32_BIT = L"Textractor: 架構不符：請使用 32 位元版本的 Textractor";
NEED_64_BIT = L"Textractor: 架構不符：請使用 64 位元版本的 Textractor";
INJECT_FAILED = L"Textractor: 無法注入";
LAUNCH_FAILED = L"Textractor: 無法啟動";
INVALID_CODE = L"Textractor: 無效代碼";
INVALID_CODEPAGE = L"Textractor: 無法轉換文字 (代碼頁無效？)";
PIPE_CONNECTED = u8"Textractor: 管道已連接";
INSERTING_HOOK = u8"Textractor: 正在置入 Hook: %s";
REMOVING_HOOK = u8"Textractor: 正在移除 Hook: %s";
HOOK_FAILED = u8"Textractor: Hook 置入失敗";
TOO_MANY_HOOKS = u8"Textractor: Hook 數量已達上限：無法置入";
HOOK_SEARCH_STARTING = u8"Textractor: 開始搜尋 Hook";
HOOK_SEARCH_INITIALIZING = u8"Textractor: 正在初始化 Hook 搜尋 (%f%%)";
NOT_ENOUGH_TEXT = u8"Textractor: 文字長度不足，無法精確搜尋";
HOOK_SEARCH_INITIALIZED = u8"Textractor: 搜尋初始化完成，建立了 %zd 個 Hook";
MAKE_GAME_PROCESS_TEXT = u8"Textractor: 請點擊遊戲內容，在接下來的 %d 秒內使遊戲強制處理文字";
HOOK_SEARCH_FINISHED = u8"Textractor: Hook 搜尋完畢，找到了 %d 條結果";
OUT_OF_RECORDS_RETRY = u8"Textractor: 搜尋紀錄已達上限，如果結果不理想請重試 (預設紀錄數已增加)";
FUNC_MISSING = u8"Textractor: 找不到函數";
MODULE_MISSING = u8"Textractor: 找不到模組";
GARBAGE_MEMORY = u8"Textractor: 記憶體內容持續變動，讀取無意義";
SEND_ERROR = u8"Textractor: 送出錯誤 (H-code 可能不正確)";
READ_ERROR = u8"Textractor: 讀取錯誤 (R-code 可能不正確)";
HIJACK_ERROR = u8"Textractor: 劫持 (Hijack) 錯誤";
COULD_NOT_FIND = u8"Textractor: 找不到文字";
TRANSLATE_TO = u8"翻譯為";
TRANSLATE_FROM = u8"來源語言";
CONFIGURE_TRANSLATION_SETTINGS = u8"請在外部翻譯程式中配置來源/目標語言與 API Key";
PORT = u8"連接埠 (Port)";
TRANSLATE_VERSION = u8"版本";
TRANSLATE_EDITON = u8"翻譯版本";
FILTER_GARBAGE = u8"過濾無意義字元";
TRANSLATE_SELECTED_THREAD_ONLY = u8"僅翻譯目前選擇的文字執行緒";
RATE_LIMIT_ALL_THREADS = u8"啟用頻率限制";
RATE_LIMIT_SELECTED_THREAD = u8"對選取的執行緒限制頻率";
USE_TRANS_CACHE = u8"使用快取的翻譯結果";
MAX_TRANSLATIONS_IN_TIMESPAN = u8"單位時間內最大請求次數";
TIMESPAN = u8"單位時間長度 (ms)";
SENTENCE_TOO_LARGE_TO_TRANS = L"要翻譯的句子太長了";
TOO_MANY_TRANS_REQUESTS = L"超出頻率限制：拒絕翻譯請求";
TRANSLATION_ERROR = L"翻譯時發生錯誤";
USE_PREV_SENTENCE_CONTEXT = u8"使用前一個句子作為上下文";
API_KEY = u8"API Key";
CHROME_LOCATION = u8"Google Chrome 安裝路徑";
START_DEVTOOLS = u8"啟動開發者工具 (DevTools)";
STOP_DEVTOOLS = u8"停止開發者工具 (DevTools)";
HIDE_CHROME = u8"隱藏 Chrome 視窗";
DEVTOOLS_STATUS = u8"開發者工具狀態";
AUTO_START = u8"自動啟動";
ERROR_START_CHROME = L"無法啟動或連接到 Chrome";
EXTRA_WINDOW_INFO = u8R"(在此按右鍵以修改設定
在視窗邊緣點擊並拖曳以移動，在視窗右下角拖曳以調整大小)";
MAX_SENTENCE_SIZE = u8"最大句子長度";
TOPMOST = u8"視窗固定在最上層";
DICTIONARY = u8"字典";
DICTIONARY_INSTRUCTIONS = u8R"(此檔案僅用於 Extra Window 擴充功能的「字典」功能。
它使用 Textractor 特有的自定義格式，不建議手動編寫。
你應該在網路搜尋此格式的詞典（推薦：https://github.com/Artikash/Textractor-Dictionaries/releases）。
或者，如果你是程式設計師，可以參考以下資訊撰寫腳本轉換其他格式的詞典。
安裝詞典後，在 Extra Window 中將滑鼠懸停在文字上即可查詞，可捲動查看所有符合項目。
定義格式如下：|TERM|Hola<<ignored|TERM|hola|TERM|Bonjour|TERM|bonjour|DEFINITION|hello|END|
術語和定義支援富文本 (HTML 子集)，將正確顯示格式。
詞形變化格式：|ROOT|1<<noun|INFLECTS TO|(\w*)s|NAME| plural|END|
Textractor 會檢查術語是否符合正規表達式，若符合則遞迴搜尋根詞。
根詞透過替換正規表達式擷取群組產生（0 代表完整匹配）。
注意：此過程可能導致無窮迴圈或堆疊溢位，請務必小心。
正規表達式使用 QRegularExpression 的 Unicode 語法。
Textractor 將顯示最終的根詞（原形），以及在追溯該根詞過程中涉及的所有詞形變化。
<< 之後的內容在顯示時會被忽略，通常用於儲存詞性資訊。
檔案必須使用 UTF-8 編碼。)";
SHOW_ORIGINAL = u8"顯示原文";
SHOW_ORIGINAL_INFO = u8R"(原文將會隱藏
僅當此擴充功能位於翻譯擴充功能之後時有效)";
ORIGINAL_AFTER_TRANSLATION = u8"將原文顯示在翻譯文字之後";
SIZE_LOCK = u8"固定視窗大小";
POSITION_LOCK = u8"固定視窗位置";
CENTERED_TEXT = u8"文字置中";
AUTO_RESIZE_WINDOW_HEIGHT = u8"自動調整視窗高度";
CLICK_THROUGH = u8"點擊穿透\tAlt+X";
HIDE_MOUSEOVER = u8"滑鼠經過時隱藏視窗";
HIDE_TEXT = u8"隱藏/顯示文字\tAlt+T";
OPACITY = u8"不透明度";
BG_COLOR = u8"背景顏色";
TEXT_COLOR = u8"文字顏色";
TEXT_OUTLINE = u8"文字外框";
OUTLINE_COLOR = u8"外框顏色";
OUTLINE_SIZE = u8"外框大小";
OUTLINE_SIZE_INFO = u8"外框單位為像素，建議保持在字體大小的 20% 以下";
FONT = u8"字體";
TIMER_HIDE_TEXT = u8"定時隱藏文字";
TEXT_TIMEOUT = u8"文字停留時間 (毫秒, 0=停用)";
TEXT_TIMEOUT_ADD_PER_CHAR = u8"每個字元額外增加的顯示時間 (毫秒)";
LUA_INTRO = u8R"(--[[
ProcessSentence 是 Textractor 每接收到一句文字時都會呼叫的函數。

參數 sentence: Textractor 接收到的文字 (UTF-8), 資料類型為 string。
參數 sentenceInfo: 用於儲存文字相關資訊的表 (Table), 資料類型為 table。

如果你回傳一個字串，文字將被轉換為該字串。
如果回傳 nil，該文字將不會被修改。

此擴充功能使用了數個 Lua 解釋器副本以確保執行緒安全。
在 ProcessSentence 函數中對全域變數的修改可能不會持久生效。

sentenceInfo 表有以下索引鍵：
"current select": 除非文字屬於使用者目前選取的執行緒，否則為 0。資料類型為 number。
"process id": 此句文字所屬的程序 ID (PID)。0 表示主控台與剪貼板執行緒。資料類型為 number。
"text number": 目前文字執行緒的編號。隨執行緒建立依序遞增。0 為主控台，1 為剪貼板。資料類型為 number。
--]]
function ProcessSentence(sentence, sentenceInfo)
  -- 在此處撰寫您的程式碼...
end)";
LOAD_SCRIPT = u8"載入腳本";
LUA_ERROR = L"Lua 錯誤";
REGEX_FILTER = u8"正規表達式過濾器";
INVALID_REGEX = u8"無效的正規表達式";
CURRENT_FILTER = u8"目前過濾中: %1";
REPLACER_INSTRUCTIONS = LR"(使用 "Replacer" 擴充功能時會使用此檔案
替換指令必須遵循以下格式：
|ORIG|原文|BECOMES|替換文字|END|
此檔案中替換指令以外的所有文字都會被忽略。
插入符號 (^) 可作為萬用字元，比對任何單一字元。
原文中的空白字元會被忽略，但替換文字可以包含空格、換行符號等。
此檔案必須使用 Unicode 編碼 (UTF-16 Little Endian)。)";
REGEX_REPLACER_INSTRUCTIONS = LR"(使用 "Regex Replacer" 擴充功能時會使用此檔案
替換指令必須遵循以下格式：
|REGEX|正規表達式|BECOMES|替換文字|MODIFIER|修飾符|END|
替換文字可以透過 $[編號] 來引用擷取群組 (例如: $1 引用第 1 個擷取群組)。
修飾符可以包含以下選項：
"g" 全域替換。
"i" 忽略大小寫。
如果留空，則僅替換第一個匹配項且區分大小寫。
此檔案中替換指令以外的所有文字都會被忽略。
此檔案必須使用 Unicode 編碼 (UTF-16 Little Endian)。
學習、建構與測試正規表達式：https://regexr.com/)";
THREAD_LINKER = u8"執行緒連結器";
LINK = u8"連結";
UNLINK = u8"取消連結";
THREAD_LINK_FROM = u8"欲連結的執行緒編號";
THREAD_LINK_TO = u8"連結到的目標執行緒編號";
HEXADECIMAL = u8"十六進位";
LANGUAGE_SETTING = u8"語言 (需重啟)";
LANGUAGE_RESTART_NOTICE = u8"語言變更將在重新啟動 Textractor 後生效";
CHECK_UPDATE = u8"啟動時檢查 texthook 更新";
ORIGINAL_FONT = u8"原文語言字型";
TRANSLATED_FONT = u8"翻譯語言字型";
WINHTTP_TIMEOUT = L"要求逾時";
WINHTTP_NAME_NOT_RESOLVED = L"DNS 解析失敗";
WINHTTP_CANNOT_CONNECT = L"無法連線至伺服器";
WINHTTP_CONNECTION_ERROR = L"連線已中斷";
WINHTTP_SECURE_FAILURE = L"TLS/SSL 握手失敗";
WINHTTP_INVALID_SERVER_RESPONSE = L"無效的伺服器回應";
WINHTTP_OPERATION_CANCELLED = L"操作已取消";
UNKNOWN_ERROR = L"未知錯誤";
CHECKING_UPDATE = L"正在檢查更新...";
OPEN_TEXTHOOK_FAILED = L"無法開啟 texthook.dll";
CHECK_UPDATE_FAILED = L"檢查更新失敗: %s";
CHECK_UPDATE_FAILED_CODE = L"檢查更新失敗: %s (代碼=%u)";
CHECK_UPDATE_FAILED_HTTP = L"檢查更新失敗: HTTP 狀態碼 %u";
CHECK_UPDATE_FAILED_EMPTY_RESPONSE = L"檢查更新失敗: 伺服器回應為空";
CHECK_UPDATE_FAILED_MALFORMED_RESPONSE = L"檢查更新失敗: JSON 回應格式錯誤";
CHECK_UPDATE_FAILED_UNKNOWN = L"檢查更新失敗: 伺服器回傳未知錯誤";
CHECK_UPDATE_FAILED_UNEXPECTED_RESPONSE = L"更新伺服器回應異常。\n請嘗試使用瀏覽器訪問更新伺服器以確認狀況: https://api.iloli.one";
TEXTHOOK_UPDATE_AVAILABLE = L"發現新版 Texthook！\n目前版本: %s, 最新版本: %s\n下載連結: %s";
TEXTHOOK_IS_LATEST = L"Texthook 已是最新版本。";
TENCENT_AUTH_PROMPT = L"請在 API Key 欄位中填寫騰訊雲翻譯的 SecretId|SecretKey";
LINGOCLOUD_AUTH_PROMPT = L"請在 API Key 欄位中填寫彩雲小譯的 API Token";
TRANSLATION_NO_TRANSLATION_FOUND = L"回應中找不到翻譯結果";
TRANSLATION_JSON_PARSE_ERROR = L"JSON 解析錯誤";
TRANSLATION_KEY_ERROR = L"翻譯映射表中的索引鍵 (Key) 錯誤";
TRANSLATION_EXCEPTION_OCCURRED = L"發生異常";
TRANSLATION_UNKNOWN_ERROR = L"翻譯過程中發生未知錯誤";
TRANSLATION_EMPTY_RESPONSE = L"翻譯 API 回應為空";
TRANSLATION_RESPONSE_PARSE_DATA_EMPTY = L"解析回應後資料列為空";
TRANSLATION_INVALID_JSON_FORMAT = L"無效的 JSON 回應格式";
TRANSLATION_UNEXPECTED_STRUCTURE = L"非預期的回應結構";
TRANSLATION_INVALID_DATA_STRUCTURE = L"無效的翻譯資料結構";
TRANSLATION_EMPTY_ARRAY = L"翻譯陣列為空";
TRANSLATION_INVALID_ENTRY = L"無效的翻譯條目";
TRANSLATION_EMPTY_SEGMENTS = L"翻譯分段 (Segments) 為空";
TRANSLATION_NO_TEXT_IN_SEGMENTS = L"分段中找不到翻譯文字";
TRANSLATION_RETRY_LIMIT_REACHED = L"已達重試次數上限";
ALIYUN_CSRF_TOKEN_NOT_FOUND = L"回應中找不到 CSRF 權杖 (Token)";
ALIYUN_INVALID_API_KEY_FORMAT = L"API Key 格式無效。應為: accessKeyId|accessKeySecret";
ALIYUN_API_ERROR = L"阿里雲 API 錯誤";
BING_TOKEN_RESPONSE_EMPTY = L"權杖 (Token) 回應為空";
BING_COULD_NOT_ACQUIRE_TOKEN = L"無法取得權杖 (Token)";
BING_TOKEN_NOT_FOUND = L"找不到權杖 (Token)";
BAIDU_MD5_SIGNATURE_FAILED = L"MD5 簽章產生失敗。";