// Vietnamese translations
// Generated by Gemini

NATIVE_LANGUAGE = "Vietnamese";
ATTACH = u8"Gắn vào game";
LAUNCH = u8"Chạy game";
CONFIG = u8"Cấu hình game";
DETACH = u8"Gỡ khỏi game";
FORGET = u8"Quên game này";
RESTART_AS_ADMIN = u8"Chạy lại dưới quyền Admin";
ADD_HOOK = u8"Thêm hook";
REMOVE_HOOKS = u8"Xóa hook";
SAVE_HOOKS = u8"Lưu hook";
SEARCH_FOR_HOOKS = u8"Tìm kiếm hook";
SETTINGS = u8"Cài đặt";
EXTENSIONS = u8"Tiện ích mở rộng";
SELECT_PROCESS = u8"Chọn tiến trình";
ATTACH_INFO = u8R"(Nếu bạn không thấy tiến trình muốn gắn vào, hãy thử chạy với quyền admin.
Bạn cũng có thể nhập trực tiếp ID tiến trình (PID))";
REFRESH = u8"Làm mới";
HIDE_INCOMPATIBLE_ARCHITECTURE = u8"Ẩn kiến trúc không tương thích";
SELECT_PROCESS_INFO = u8"Nếu bạn nhập tên tệp tiến trình thủ công, hãy sử dụng đường dẫn tuyệt đối";
FROM_COMPUTER = u8"Chọn từ máy tính";
PROCESSES = u8"Tiến trình (*.exe)";
CODE_INFODUMP = u8R"(Nhập mã đọc (read code)
R{S|Q|V|M}[null_length<][codepage#]@addr
HOẶC
Nhập mã hook (hook code)
H{A|B|W|H|S|Q|V|M}[F][null_length<][N][codepage#][padding+]data_offset[*deref_offset][:split_offset[*deref_offset]]@addr[:module[:func]]
Tất cả các số ngoại trừ codepage/null_length đều ở hệ thập lục phân (hex)
Codepage mặc định là 932 (Shift-JIS) nhưng có thể thay đổi trong cài đặt
A/B: ký tự codepage dạng little/big endian
W: ký tự UTF-16
H: Hai byte hex
S/Q/V/M: chuỗi codepage/UTF-16/UTF-8/hex
F: xử lý chuỗi dưới dạng các dòng văn bản đầy đủ
N: không sử dụng ngữ cảnh (context)
null_length: độ dài của ký tự kết thúc null dùng cho chuỗi
padding: độ dài dữ liệu đệm trước chuỗi (C struct { int64_t size; char string[500]; } cần padding = 8)
Giá trị âm cho data_offset/split_offset dùng để chỉ các thanh ghi
-4 cho EAX, -8 cho ECX, -C cho EDX, -10 cho EBX, -14 cho ESP, -18 cho EBP, -1C cho ESI, -20 cho EDI
-C cho RAX, -14 cho RBX, -1C cho RCX, -24 cho RDX, và tương tự cho RSP, RBP, RSI, RDI, R8-R15
* nghĩa là giải tham chiếu con trỏ (dereference) + deref_offset)";
SAVE_SETTINGS = u8"Lưu cài đặt";
EXTEN_WINDOW_INSTRUCTIONS = u8R"(Chuột phải vào danh sách để thêm hoặc xóa tiện ích mở rộng
Kéo và thả các tiện ích trong danh sách để sắp xếp lại thứ tự
(Tiện ích được sử dụng từ trên xuống dưới: thứ tự RẤT quan trọng))";
ADD_EXTENSION = u8"Thêm tiện ích";
REMOVE_EXTENSION = u8"Xóa tiện ích";
INVALID_EXTENSION = u8"%1 là tiện ích không hợp lệ";
CONFIRM_EXTENSION_OVERWRITE = u8"Một phiên bản khác của tiện ích này đã tồn tại, bạn có muốn xóa và ghi đè không?";
EXTENSION_WRITE_ERROR = u8"Lỗi khi lưu tiện ích mở rộng";
USE_JP_LOCALE = u8"Giả lập locale Nhật Bản?";
FAILED_TO_CREATE_CONFIG_FILE = u8"Không thể tạo tệp cấu hình \"%1\"";
HOOK_SEARCH_UNSTABLE_WARNING = u8"Tìm kiếm hook có thể gây mất ổn định! Hãy chuẩn bị tinh thần nếu game bị crash!";
HOOK_SEARCH_STARTING_VIEW_CONSOLE = u8"Đang khởi tạo tìm kiếm hook - vui lòng kiểm tra cửa sổ console để xem hướng dẫn tiếp theo";
SEARCH_CJK = u8"Tìm kiếm tiếng Trung/Nhật/Hàn";
SEARCH_PATTERN = u8"Mẫu tìm kiếm (mảng byte hex)";
SEARCH_DURATION = u8"Thời gian tìm kiếm (ms)";
SEARCH_MODULE = u8"Tìm kiếm trong module";
PATTERN_OFFSET = u8"Offset từ điểm bắt đầu mẫu";
MAX_HOOK_SEARCH_RECORDS = u8"Giới hạn kết quả tìm kiếm";
MIN_ADDRESS = u8"Địa chỉ tối thiểu (hex)";
MAX_ADDRESS = u8"Địa chỉ tối đa (hex)";
STRING_OFFSET = u8"String offset (hex)";
HOOK_SEARCH_FILTER = u8"Kết quả phải khớp với regex này";
TEXT = u8"Văn bản";
CODEPAGE = u8"Codepage";
SEARCH_FOR_TEXT = u8"Tìm kiếm văn bản cụ thể";
START_HOOK_SEARCH = u8"Bắt đầu tìm hook";
SAVE_SEARCH_RESULTS = u8"Lưu kết quả tìm kiếm";
TEXT_FILES = u8"Tệp văn bản (*.txt)";
DOUBLE_CLICK_TO_REMOVE_HOOK = u8"Nhấp đúp vào một hook để xóa nó";
FILTER_REPETITION = u8"Lọc lặp văn bản";
AUTO_ATTACH = u8"Tự động gắn (Auto attach)";
ATTACH_SAVED_ONLY = u8"Tự động gắn (chỉ hook đã lưu)";
SHOW_SYSTEM_PROCESSES = u8"Hiển thị tiến trình hệ thống";
DEFAULT_CODEPAGE = u8"Codepage mặc định";
FLUSH_DELAY = u8"Độ trễ đẩy dữ liệu (Flush delay)";
FLUSH_DELAY_SPACING = u8"Khoảng cách chuỗi trễ đẩy dữ liệu";
MAX_BUFFER_SIZE = u8"Kích thước bộ đệm tối đa";
MAX_HISTORY_SIZE = u8"Kích thước lịch sử tối đa";
LIMIT_STRING_LENGTH = u8"Giới hạn độ dài chuỗi (0=Tắt)";
CONFIG_JP_LOCALE = u8"Chạy với locale Nhật Bản";
CONSOLE = L"Console";
CLIPBOARD = L"Clipboard";
ABOUT = L"Textractor " ARCH L" v" VERSION LR"( tạo bởi Artikash (email: akashmozumdar@gmail.com)
Trang chủ dự án: https://github.com/Artikash/Textractor
Video hướng dẫn: https://github.com/Artikash/Textractor/blob/master/docs/TUTORIAL.md
FAQ: https://github.com/Artikash/Textractor/wiki/FAQ
Vui lòng liên hệ Artikash nếu gặp sự cố, yêu cầu tính năng hoặc thắc mắc về Textractor
Bạn có thể liên hệ qua trang chủ dự án (mục issues) hoặc qua email
Mã nguồn mở dưới bản quyền GPLv3 tại trang chủ dự án
Nếu bạn thích dự án này, hãy chia sẻ nó với mọi người! Đã đến lúc cho AGTH nghỉ hưu :))";
CL_OPTIONS = LR"(sử dụng: Textractor [-p{ID tiến trình|"tên tiến trình"}]...
ví dụ: Textractor -p4466 -p"My Game.exe" sẽ cố gắng inject vào tiến trình có ID 4466 hoặc tên My Game.exe)";
UPDATE_AVAILABLE = L"Đã có bản cập nhật: tải về tại https://github.com/Artikash/Textractor/releases";
ALREADY_INJECTED = L"Textractor: đã inject rồi";
NEED_32_BIT = L"Textractor: kiến trúc không khớp: chỉ Textractor x86 mới có thể inject tiến trình này";
NEED_64_BIT = L"Textractor: kiến trúc không khớp: chỉ Textractor x64 mới có thể inject tiến trình này";
INJECT_FAILED = L"Textractor: không thể inject";
LAUNCH_FAILED = L"Textractor: không thể chạy";
INVALID_CODE = L"Textractor: mã không hợp lệ";
INVALID_CODEPAGE = L"Textractor: không thể chuyển đổi văn bản (codepage không hợp lệ?)";
PIPE_CONNECTED = u8"Textractor: đường dẫn (pipe) đã kết nối";
INSERTING_HOOK = u8"Textractor: đang chèn hook: %s";
REMOVING_HOOK = u8"Textractor: đang xóa hook: %s";
HOOK_FAILED = u8"Textractor: chèn hook thất bại";
TOO_MANY_HOOKS = u8"Textractor: quá nhiều hook: không thể chèn thêm";
HOOK_SEARCH_STARTING = u8"Textractor: đang bắt đầu tìm kiếm hook";
HOOK_SEARCH_INITIALIZING = u8"Textractor: đang khởi tạo tìm kiếm hook (%f%%)";
NOT_ENOUGH_TEXT = u8"Textractor: không đủ văn bản để tìm kiếm chính xác";
HOOK_SEARCH_INITIALIZED = u8"Textractor: đã khởi tạo tìm kiếm hook với %zd hook";
MAKE_GAME_PROCESS_TEXT = u8"Textractor: vui lòng thao tác trong game để buộc nó xử lý văn bản trong %d giây tới";
HOOK_SEARCH_FINISHED = u8"Textractor: tìm kiếm hook kết thúc, tìm thấy %d kết quả";
OUT_OF_RECORDS_RETRY = u8"Textractor: hết hồ sơ tìm kiếm, vui lòng thử lại nếu kết quả kém (số lượng hồ sơ mặc định đã được tăng)";
FUNC_MISSING = u8"Textractor: không tìm thấy hàm";
MODULE_MISSING = u8"Textractor: không tìm thấy module";
GARBAGE_MEMORY = u8"Textractor: bộ nhớ thay đổi liên tục, không thể đọc dữ liệu có ích";
SEND_ERROR = u8"Textractor: Lỗi gửi (Send ERROR) (có khả năng là H-code không ổn định hoặc sai)";
READ_ERROR = u8"Textractor: Lỗi đọc (Reader ERROR) (có khả năng là R-code sai)";
HIJACK_ERROR = u8"Textractor: Lỗi Hijack";
COULD_NOT_FIND = u8"Textractor: không tìm thấy văn bản";
TRANSLATE_TO = u8"Dịch sang";
TRANSLATE_FROM = u8"Dịch từ";
CONFIGURE_TRANSLATION_SETTINGS = u8"Vui lòng cấu hình ngôn ngữ nguồn/đích và mã API trong chương trình dịch thuật bên ngoài.";
PORT = u8"Cổng (Port)";
TRANSLATE_VERSION = u8"Phiên bản";
TRANSLATE_EDITON = u8"Phiên bản dịch thuật";
FILTER_GARBAGE = u8"Lọc ký tự rác";
TRANSLATE_SELECTED_THREAD_ONLY = u8"Chỉ dịch luồng văn bản được chọn";
RATE_LIMIT_ALL_THREADS = u8"Sử dụng giới hạn tốc độ (rate limiter)";
RATE_LIMIT_SELECTED_THREAD = u8"Giới hạn tốc độ luồng văn bản được chọn";
USE_TRANS_CACHE = u8"Sử dụng bộ nhớ đệm dịch thuật (cache)";
MAX_TRANSLATIONS_IN_TIMESPAN = u8"Số yêu cầu dịch tối đa trong khoảng thời gian";
TIMESPAN = u8"Khoảng thời gian (ms)";
SENTENCE_TOO_LARGE_TO_TRANS = L"Câu quá dài để dịch";
TOO_MANY_TRANS_REQUESTS = L"Vượt quá giới hạn tốc độ: từ chối thực hiện thêm yêu cầu dịch";
TRANSLATION_ERROR = L"Lỗi trong khi dịch";
USE_PREV_SENTENCE_CONTEXT = u8"Sử dụng câu trước làm ngữ cảnh";
API_KEY = u8"Mã API (API key)";
CHROME_LOCATION = u8"Vị trí tệp Google Chrome";
START_DEVTOOLS = u8"Bật DevTools";
STOP_DEVTOOLS = u8"Tắt DevTools";
HIDE_CHROME = u8"Ẩn cửa sổ Chrome";
DEVTOOLS_STATUS = u8"Trạng thái DevTools";
AUTO_START = u8"Tự động bắt đầu";
ERROR_START_CHROME = L"không thể khởi động Chrome hoặc kết nối với nó";
EXTRA_WINDOW_INFO = u8R"(Chuột phải để thay đổi cài đặt
Nhấn và kéo cạnh cửa sổ để di chuyển, hoặc góc dưới bên phải để thay đổi kích thước)";
MAX_SENTENCE_SIZE = u8"Kích thước câu tối đa";
TOPMOST = u8"Luôn hiện trên cùng";
DICTIONARY = u8"Từ điển";
DICTIONARY_INSTRUCTIONS = u8R"(Tệp này chỉ được sử dụng cho tính năng "Từ điển" của tiện ích Extra Window.
Nó sử dụng một định dạng tùy chỉnh dành riêng cho Textractor và không nhằm mục đích viết thủ công.
Bạn nên tìm kiếm các bộ từ điển có định dạng này trên mạng (https://github.com/Artikash/Textractor-Dictionaries/releases là một nơi tốt để bắt đầu).
Ngoài ra, nếu bạn là lập trình viên, bạn có thể viết script để chuyển đổi từ điển từ định dạng khác dựa trên thông tin bên dưới.
Khi đã có từ điển, để tra cứu văn bản trong Extra Window, hãy di chuột lên văn bản đó. Bạn có thể cuộn qua tất cả các định nghĩa phù hợp.
Các định nghĩa được định dạng như sau:|TERM|Hola<<ignored|TERM|hola|TERM|Bonjour|TERM|bonjour|DEFINITION|hello|END|
Từ gốc và định nghĩa có thể bao gồm văn bản định dạng (rich text - https://doc.qt.io/qt-5/richtext-html-subset.html) để hiển thị đẹp hơn.
Các biến thể chia từ (Inflections) được định dạng như sau:|ROOT|1<<noun|INFLECTS TO|(\w*)s|NAME| plural|END|
Textractor sẽ kiểm tra xem một thuật ngữ có khớp với regex biến thể hay không, nếu khớp, nó sẽ tìm kiếm đệ quy về từ gốc.
Từ gốc được tạo ra bằng cách thay thế mỗi số bằng nhóm bắt (capture group) regex tương ứng (với 0 là toàn bộ kết quả khớp).
Quá trình này dễ dẫn đến vòng lặp vô tận hoặc tràn ngăn xếp (stack overflow). Bạn có trách nhiệm tránh việc đó.
Regex biến thể sử dụng cú pháp unicode QRegularExpression (https://doc.qt.io/qt-5/qregularexpression.html).
Textractor sẽ hiển thị từ gốc cuối cùng cũng như tất cả các biến thể đã dùng để đi đến từ gốc đó.
Tuy nhiên, phần văn bản trong thuật ngữ đứng sau ký hiệu << sẽ bị bỏ qua khi hiển thị. Phần này dùng để lưu thông tin từ loại.
Tệp này phải được mã hóa theo chuẩn UTF-8.)";
SHOW_ORIGINAL = u8"Văn bản gốc";
SHOW_ORIGINAL_INFO = u8R"(Văn bản gốc sẽ không được hiển thị
Chỉ hoạt động nếu tiện ích này được dùng ngay sau một tiện ích dịch thuật)";
ORIGINAL_AFTER_TRANSLATION = u8"Văn bản gốc sau khi dịch";
SIZE_LOCK = u8"Khóa kích thước";
POSITION_LOCK = u8"Khóa vị trí";
CENTERED_TEXT = u8"Căn giữa văn bản";
AUTO_RESIZE_WINDOW_HEIGHT = u8"Tự động chỉnh chiều cao cửa sổ";
CLICK_THROUGH = u8"Nhấp xuyên qua\tAlt+X";
HIDE_MOUSEOVER = u8"Ẩn khi di chuột lên trên";
HIDE_TEXT = u8"Ẩn/Hiện văn bản\tAlt+T";
OPACITY = u8"Độ mờ";
BG_COLOR = u8"Màu nền";
TEXT_COLOR = u8"Màu chữ";
TEXT_OUTLINE = u8"Viền chữ";
OUTLINE_COLOR = u8"Màu viền";
OUTLINE_SIZE = u8"Kích thước viền";
OUTLINE_SIZE_INFO = u8"Kích thước tính bằng pixel (khuyến nghị để dưới 20% cỡ chữ)";
FONT = u8"Phông chữ";
TIMER_HIDE_TEXT = u8"Hẹn giờ ẩn văn bản";
TEXT_TIMEOUT = u8"Thời gian chờ (ms, 0=tắt)";
TEXT_TIMEOUT_ADD_PER_CHAR = u8"Thời gian chờ cộng thêm mỗi ký tự (ms)";
LUA_INTRO = u8R"(--[[
ProcessSentence được gọi mỗi khi Textractor nhận được một câu văn bản.

Tham số sentence: câu nhận được bởi Textractor (UTF-8).
Tham số sentenceInfo: bảng chứa thông tin linh tinh về câu đó.

Nếu bạn trả về một chuỗi, câu sẽ được chuyển thành chuỗi đó.
Nếu bạn trả về nil, câu sẽ giữ nguyên không đổi.

Tiện ích này sử dụng nhiều bản sao của trình thông dịch Lua để đảm bảo an toàn luồng (thread safety).
Các thay đổi đối với biến toàn cục từ ProcessSentence không được đảm bảo sẽ tồn tại lâu dài.

Các thuộc tính trong sentenceInfo:
"current select": bằng 0 trừ khi câu nằm trong luồng văn bản hiện đang được người dùng chọn.
"process id": ID tiến trình mà câu đang gửi đến. Bằng 0 đối với console và clipboard.
"text number": số thứ tự của luồng văn bản hiện tại. Tăng dần khi các luồng văn bản mới được tạo. 0 cho console, 1 cho clipboard.
--]]
function ProcessSentence(sentence, sentenceInfo)
  --Viết mã của bạn tại đây...
end)";
LOAD_SCRIPT = u8"Tải script";
LUA_ERROR = L"Lỗi Lua: %s";
REGEX_FILTER = u8"Bộ lọc Regex";
INVALID_REGEX = u8"Regex không hợp lệ";
CURRENT_FILTER = u8"Hiện đang lọc: %1";
REPLACER_INSTRUCTIONS = LR"(Tệp này chỉ có tác dụng khi tiện ích "Replacer" được sử dụng.
Các lệnh thay thế phải được định dạng như sau:
|ORIG|văn_bản_gốc|BECOMES|văn_bản_thay_thế|END|
Mọi văn bản trong tệp này nằm ngoài lệnh thay thế đều bị bỏ qua.
Ký tự dấu mũ (^) đóng vai trò là ký tự đại diện khớp với bất kỳ ký tự đơn nào khác.
Khoảng trắng trong văn_bản_gốc sẽ bị bỏ qua, nhưng văn_bản_thay_thế có thể chứa dấu cách, xuống dòng, v.v.
Tệp này phải được mã hóa theo chuẩn Unicode (UTF-16 Little Endian).)";
REGEX_REPLACER_INSTRUCTIONS = LR"(Tệp này chỉ có tác dụng khi tiện ích "Regex Replacer" được sử dụng.
Các lệnh thay thế phải được định dạng như sau:
|REGEX|biểu_thức_chính_quy|BECOMES|văn_bản_thay_thế|MODIFIER|modifiers|END|
văn_bản_thay_thế có thể tham chiếu đến các nhóm bắt bằng dấu $ theo sau là số thứ tự (ví dụ: $1 tham chiếu đến nhóm bắt đầu tiên).
modifiers có thể chứa các giá trị sau:
"g" thay thế trên phạm vi toàn cục (global).
"i" thay thế không phân biệt chữ hoa chữ thường.
Nếu để trống, việc thay thế chỉ áp dụng cho kết quả khớp đầu tiên và có phân biệt chữ hoa chữ thường.
Mọi văn bản trong tệp này nằm ngoài lệnh thay thế đều bị bỏ qua.
Tệp này phải được mã hóa theo chuẩn Unicode (UTF-16 Little Endian).
Học, xây dựng và kiểm tra Biểu thức chính quy tại: https://regexr.com/)";
THREAD_LINKER = u8"Liên kết luồng (Thread Linker)";
LINK = u8"Liên kết";
UNLINK = u8"Hủy liên kết";
THREAD_LINK_FROM = u8"Số luồng nguồn cần liên kết";
THREAD_LINK_TO = u8"Số luồng đích cần liên kết";
HEXADECIMAL = u8"Hệ thập lục phân";
LANGUAGE_SETTING = u8"Ngôn ngữ (yêu cầu khởi động lại)";
LANGUAGE_RESTART_NOTICE = u8"Thay đổi ngôn ngữ sẽ có hiệu lực sau khi khởi động lại Textractor";
CHECK_UPDATE = u8"Kiểm tra cập nhật texthook khi khởi động";
ORIGINAL_FONT = u8"Phông chữ gốc";
TRANSLATED_FONT = u8"Phông chữ đã dịch";
WINHTTP_TIMEOUT = L"yêu cầu đã quá hạn (timeout)";
WINHTTP_NAME_NOT_RESOLVED = L"lỗi phân giải DNS";
WINHTTP_CANNOT_CONNECT = L"không thể kết nối tới máy chủ";
WINHTTP_CONNECTION_ERROR = L"kết nối bị ngắt";
WINHTTP_SECURE_FAILURE = L"bắt tay TLS/SSL thất bại";
WINHTTP_INVALID_SERVER_RESPONSE = L"phản hồi máy chủ không hợp lệ";
WINHTTP_OPERATION_CANCELLED = L"yêu cầu đã bị hủy";
UNKNOWN_ERROR = L"lỗi không xác định";
CHECKING_UPDATE = L"Đang kiểm tra cập nhật...";
OPEN_TEXTHOOK_FAILED = L"Không thể mở tệp texthook.dll.";
CHECK_UPDATE_FAILED = L"Kiểm tra cập nhật thất bại: %s";
CHECK_UPDATE_FAILED_CODE = L"Kiểm tra cập nhật thất bại: %s (mã=%u).";
CHECK_UPDATE_FAILED_HTTP = L"Kiểm tra cập nhật thất bại: Trạng thái HTTP %u.";
CHECK_UPDATE_FAILED_EMPTY_RESPONSE = L"Kiểm tra cập nhật thất bại: máy chủ phản hồi trống.";
CHECK_UPDATE_FAILED_MALFORMED_RESPONSE = L"Kiểm tra cập nhật thất bại: phản hồi JSON sai định dạng.";
CHECK_UPDATE_FAILED_UNKNOWN = L"Kiểm tra cập nhật thất bại: máy chủ trả về lỗi không xác định.";
CHECK_UPDATE_FAILED_UNEXPECTED_RESPONSE = L"Phản hồi không mong đợi từ máy chủ cập nhật.\nHãy thử truy cập máy chủ cập nhật bằng trình duyệt bên ngoài để xem chuyện gì đang xảy ra: https://api.iloli.one";
TEXTHOOK_UPDATE_AVAILABLE = L"Đã tìm thấy bản cập nhật Texthook!\nHiện tại: %s, Mới: %s\nTải về: %s";
TEXTHOOK_IS_LATEST = L"Texthook đã ở phiên bản mới nhất.";
TENCENT_AUTH_PROMPT = L"Vui lòng điền SecretId|SecretKey cho Tencent Cloud Translation vào trường mã API";
LINGOCLOUD_AUTH_PROMPT = L"Vui lòng điền mã Token API cho Lingocloud Translation vào trường mã API";
TRANSLATION_NO_TRANSLATION_FOUND = L"Không tìm thấy bản dịch trong phản hồi";
TRANSLATION_JSON_PARSE_ERROR = L"Lỗi phân tích cú pháp JSON";
TRANSLATION_KEY_ERROR = L"Lỗi khóa (key error) trong bản đồ dịch thuật";
TRANSLATION_EXCEPTION_OCCURRED = L"Đã xảy ra ngoại lệ";
TRANSLATION_UNKNOWN_ERROR = L"Lỗi không xác định trong khi dịch";
TRANSLATION_EMPTY_RESPONSE = L"Phản hồi trống từ API dịch thuật";
TRANSLATION_RESPONSE_PARSE_DATA_EMPTY = L"Dòng dữ liệu trống sau khi phân tích phản hồi";
TRANSLATION_INVALID_JSON_FORMAT = L"Định dạng phản hồi JSON không hợp lệ";
TRANSLATION_UNEXPECTED_STRUCTURE = L"Cấu trúc phản hồi không mong đợi";
TRANSLATION_INVALID_DATA_STRUCTURE = L"Cấu trúc dữ liệu dịch thuật không hợp lệ";
TRANSLATION_EMPTY_ARRAY = L"Mảng dịch thuật trống";
TRANSLATION_INVALID_ENTRY = L"Mục dịch thuật không hợp lệ";
TRANSLATION_EMPTY_SEGMENTS = L"Các phân đoạn dịch thuật trống";
TRANSLATION_NO_TEXT_IN_SEGMENTS = L"Không tìm thấy văn bản dịch trong các phân đoạn";
TRANSLATION_RETRY_LIMIT_REACHED = L"đã đạt giới hạn thử lại";
ALIYUN_CSRF_TOKEN_NOT_FOUND = L"Không tìm thấy token CSRF trong phản hồi";
ALIYUN_INVALID_API_KEY_FORMAT = L"Định dạng mã API không hợp lệ. Mong đợi: accessKeyId|accessKeySecret";
ALIYUN_API_ERROR = L"Lỗi API Aliyun";
BING_TOKEN_RESPONSE_EMPTY = L"phản hồi token trống";
BING_COULD_NOT_ACQUIRE_TOKEN = L"không thể lấy được token";
BING_TOKEN_NOT_FOUND = L"không tìm thấy token";
BAIDU_MD5_SIGNATURE_FAILED = L"Tạo chữ ký MD5 thất bại.";