#include "qtcommon.h"
#include "translatewrapper.h"
#include "network.h"

extern const wchar_t* TRANSLATION_ERROR;
extern const wchar_t* BING_TOKEN_RESPONSE_EMPTY;
extern const wchar_t* BING_COULD_NOT_ACQUIRE_TOKEN;

const char* TRANSLATION_PROVIDER = "Bing Translate2";
const char* GET_API_KEY_FROM = "https://www.microsoft.com/en-us/translator/business/trial/#get-started";
extern const QStringList languagesTo
{
	"Afrikaans",
	"Amharic",
	"Arabic",
	"Assamese",
	"Azerbaijani",
	"Bashkir",
	"Bulgarian",
	"Bhojpuri",
	"Bangla",
	"Tibetan",
	"Bodo",
	"Bosnian",
	"Catalan",
	"Czech",
	"Welsh",
	"Danish",
	"German",
	"Dogri",
	"Lower Sorbian",
	"Divehi",
	"Greek",
	"English",
	"Spanish",
	"Estonian",
	"Basque",
	"Persian",
	"Finnish",
	"Filipino",
	"Fijian",
	"Faroese",
	"French",
	"French (Canada)",
	"Irish",
	"Galician",
	"Konkani",
	"Gujarati",
	"Hausa",
	"Hebrew",
	"Hindi",
	"Chhattisgarhi",
	"Croatian",
	"Upper Sorbian",
	"Haitian Creole",
	"Hungarian",
	"Armenian",
	"Indonesian",
	"Igbo",
	"Inuinnaqtun",
	"Icelandic",
	"Italian",
	"Inuktitut",
	"Inuktitut (Latin)",
	"Japanese",
	"Georgian",
	"Kazakh",
	"Khmer",
	"Kurdish (Northern)",
	"Kannada",
	"Korean",
	"Kashmiri",
	"Kurdish (Central)",
	"Kyrgyz",
	"Lingala",
	"Lao",
	"Lithuanian",
	"Ganda",
	"Latvian",
	"Chinese (Literary)",
	"Maithili",
	"Malagasy",
	"Maori",
	"Macedonian",
	"Malayalam",
	"Mongolian (Cyrillic)",
	"Mongolian (Traditional)",
	"Manipuri",
	"Marathi",
	"Malay",
	"Maltese",
	"Hmong Daw",
	"Myanmar (Burmese)",
	"Norwegian",
	"Nepali",
	"Dutch",
	"Sesotho sa Leboa",
	"Nyanja",
	"Odia",
	"Queretaro Otomi",
	"Punjabi",
	"Polish",
	"Dari",
	"Pashto",
	"Portuguese (Brazil)",
	"Portuguese (Portugal)",
	"Romanian",
	"Russian",
	"Rundi",
	"Kinyarwanda",
	"Sindhi",
	"Sinhala",
	"Slovak",
	"Slovenian",
	"Samoan",
	"Shona",
	"Somali",
	"Albanian",
	"Serbian (Cyrillic)",
	"Serbian (Latin)",
	"Sesotho",
	"Swedish",
	"Swahili",
	"Tamil",
	"Telugu",
	"Thai",
	"Tigrinya",
	"Turkmen",
	"Klingon (Latin)",
	"Klingon (pIqaD)",
	"Setswana",
	"Tongan",
	"Turkish",
	"Tatar",
	"Tahitian",
	"Uyghur",
	"Ukrainian",
	"Urdu",
	"Uzbek (Latin)",
	"Vietnamese",
	"Xhosa",
	"Yoruba",
	"Yucatec Maya",
	"Cantonese (Traditional)",
	"Chinese Simplified",
	"Chinese Traditional",
	"Zulu",
}, languagesFrom = languagesTo;
extern const std::unordered_map<std::wstring, std::wstring> codes
{
	{ { L"Afrikaans"}, { L"af" } },
	{ { L"Amharic"}, { L"am" } },
	{ { L"Arabic"}, { L"ar" } },
	{ { L"Assamese"}, { L"as" } },
	{ { L"Azerbaijani"}, { L"az" } },
	{ { L"Bashkir"}, { L"ba" } },
	{ { L"Bulgarian"}, { L"bg" } },
	{ { L"Bhojpuri"}, { L"bho" } },
	{ { L"Bangla"}, { L"bn" } },
	{ { L"Tibetan"}, { L"bo" } },
	{ { L"Bodo"}, { L"brx" } },
	{ { L"Bosnian"}, { L"bs" } },
	{ { L"Catalan"}, { L"ca" } },
	{ { L"Czech"}, { L"cs" } },
	{ { L"Welsh"}, { L"cy" } },
	{ { L"Danish"}, { L"da" } },
	{ { L"German"}, { L"de" } },
	{ { L"Dogri"}, { L"doi" } },
	{ { L"Lower Sorbian"}, { L"dsb" } },
	{ { L"Divehi"}, { L"dv" } },
	{ { L"Greek"}, { L"el" } },
	{ { L"English"}, { L"en" } },
	{ { L"Spanish"}, { L"es" } },
	{ { L"Estonian"}, { L"et" } },
	{ { L"Basque"}, { L"eu" } },
	{ { L"Persian"}, { L"fa" } },
	{ { L"Finnish"}, { L"fi" } },
	{ { L"Filipino"}, { L"fil" } },
	{ { L"Fijian"}, { L"fj" } },
	{ { L"Faroese"}, { L"fo" } },
	{ { L"French"}, { L"fr" } },
	{ { L"French (Canada)"}, { L"fr-CA" } },
	{ { L"Irish"}, { L"ga" } },
	{ { L"Galician"}, { L"gl" } },
	{ { L"Konkani"}, { L"gom" } },
	{ { L"Gujarati"}, { L"gu" } },
	{ { L"Hausa"}, { L"ha" } },
	{ { L"Hebrew"}, { L"he" } },
	{ { L"Hindi"}, { L"hi" } },
	{ { L"Chhattisgarhi"}, { L"hne" } },
	{ { L"Croatian"}, { L"hr" } },
	{ { L"Upper Sorbian"}, { L"hsb" } },
	{ { L"Haitian Creole"}, { L"ht" } },
	{ { L"Hungarian"}, { L"hu" } },
	{ { L"Armenian"}, { L"hy" } },
	{ { L"Indonesian"}, { L"id" } },
	{ { L"Igbo"}, { L"ig" } },
	{ { L"Inuinnaqtun"}, { L"ikt" } },
	{ { L"Icelandic"}, { L"is" } },
	{ { L"Italian"}, { L"it" } },
	{ { L"Inuktitut"}, { L"iu" } },
	{ { L"Inuktitut (Latin)"}, { L"iu-Latn" } },
	{ { L"Japanese"}, { L"ja" } },
	{ { L"Georgian"}, { L"ka" } },
	{ { L"Kazakh"}, { L"kk" } },
	{ { L"Khmer"}, { L"km" } },
	{ { L"Kurdish (Northern)"}, { L"kmr" } },
	{ { L"Kannada"}, { L"kn" } },
	{ { L"Korean"}, { L"ko" } },
	{ { L"Kashmiri"}, { L"ks" } },
	{ { L"Kurdish (Central)"}, { L"ku" } },
	{ { L"Kyrgyz"}, { L"ky" } },
	{ { L"Lingala"}, { L"ln" } },
	{ { L"Lao"}, { L"lo" } },
	{ { L"Lithuanian"}, { L"lt" } },
	{ { L"Ganda"}, { L"lug" } },
	{ { L"Latvian"}, { L"lv" } },
	{ { L"Chinese (Literary)"}, { L"lzh" } },
	{ { L"Maithili"}, { L"mai" } },
	{ { L"Malagasy"}, { L"mg" } },
	{ { L"Maori"}, { L"mi" } },
	{ { L"Macedonian"}, { L"mk" } },
	{ { L"Malayalam"}, { L"ml" } },
	{ { L"Mongolian (Cyrillic)"}, { L"mn-Cyrl" } },
	{ { L"Mongolian (Traditional)"}, { L"mn-Mong" } },
	{ { L"Manipuri"}, { L"mni" } },
	{ { L"Marathi"}, { L"mr" } },
	{ { L"Malay"}, { L"ms" } },
	{ { L"Maltese"}, { L"mt" } },
	{ { L"Hmong Daw"}, { L"mww" } },
	{ { L"Myanmar (Burmese)"}, { L"my" } },
	{ { L"Norwegian"}, { L"nb" } },
	{ { L"Nepali"}, { L"ne" } },
	{ { L"Dutch"}, { L"nl" } },
	{ { L"Sesotho sa Leboa"}, { L"nso" } },
	{ { L"Nyanja"}, { L"nya" } },
	{ { L"Odia"}, { L"or" } },
	{ { L"Queretaro Otomi"}, { L"otq" } },
	{ { L"Punjabi"}, { L"pa" } },
	{ { L"Polish"}, { L"pl" } },
	{ { L"Dari"}, { L"prs" } },
	{ { L"Pashto"}, { L"ps" } },
	{ { L"Portuguese (Brazil)"}, { L"pt" } },
	{ { L"Portuguese (Portugal)"}, { L"pt-PT" } },
	{ { L"Romanian"}, { L"ro" } },
	{ { L"Russian"}, { L"ru" } },
	{ { L"Rundi"}, { L"run" } },
	{ { L"Kinyarwanda"}, { L"rw" } },
	{ { L"Sindhi"}, { L"sd" } },
	{ { L"Sinhala"}, { L"si" } },
	{ { L"Slovak"}, { L"sk" } },
	{ { L"Slovenian"}, { L"sl" } },
	{ { L"Samoan"}, { L"sm" } },
	{ { L"Shona"}, { L"sn" } },
	{ { L"Somali"}, { L"so" } },
	{ { L"Albanian"}, { L"sq" } },
	{ { L"Serbian (Cyrillic)"}, { L"sr-Cyrl" } },
	{ { L"Serbian (Latin)"}, { L"sr-Latn" } },
	{ { L"Sesotho"}, { L"st" } },
	{ { L"Swedish"}, { L"sv" } },
	{ { L"Swahili"}, { L"sw" } },
	{ { L"Tamil"}, { L"ta" } },
	{ { L"Telugu"}, { L"te" } },
	{ { L"Thai"}, { L"th" } },
	{ { L"Tigrinya"}, { L"ti" } },
	{ { L"Turkmen"}, { L"tk" } },
	{ { L"Klingon (Latin)"}, { L"tlh-Latn" } },
	{ { L"Klingon (pIqaD)"}, { L"tlh-Piqd" } },
	{ { L"Setswana"}, { L"tn" } },
	{ { L"Tongan"}, { L"to" } },
	{ { L"Turkish"}, { L"tr" } },
	{ { L"Tatar"}, { L"tt" } },
	{ { L"Tahitian"}, { L"ty" } },
	{ { L"Uyghur"}, { L"ug" } },
	{ { L"Ukrainian"}, { L"uk" } },
	{ { L"Urdu"}, { L"ur" } },
	{ { L"Uzbek (Latin)"}, { L"uz" } },
	{ { L"Vietnamese"}, { L"vi" } },
	{ { L"Xhosa"}, { L"xh" } },
	{ { L"Yoruba"}, { L"yo" } },
	{ { L"Yucatec Maya"}, { L"yua" } },
	{ { L"Cantonese (Traditional)"}, { L"yue" } },
	{ { L"Chinese Simplified"}, { L"zh-Hans" } },
	{ { L"Chinese Traditional"}, { L"zh-Hant" } },
	{ { L"Zulu"}, { L"zu" } },
	{ { L"?" }, { L"auto-detect" } }
};

bool translateSelectedOnly = false, useRateLimiter = true, rateLimitSelected = false, useCache = true, useFilter = true;
int tokenCount = 30, rateLimitTimespan = 60000, maxSentenceSize = 1000;

static std::atomic<long long> tokenFetchTime = 0;

bool isTokenExpired() {
	long long currentTime = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
	return tokenFetchTime + 9 * 60 <= currentTime;
}

std::pair<bool, std::wstring> Translate(const std::wstring& text, TranslationParam tlp)
{
	if (!tlp.authKey.empty())
	{
		std::wstring translateFromComponent = tlp.translateFrom == L"?" ? L"" : L"&from=" + codes.at(tlp.translateFrom);
		if (HttpRequest httpRequest{
			L"Mozilla/5.0 Textractor",
			L"api.cognitive.microsofttranslator.com",
			L"POST",
			FormatString(L"/translate?api-version=3.0&to=%s%s", codes.at(tlp.translateTo), translateFromComponent).c_str(),
			FormatString(R"([{"text":"%s"}])", JSON::Escape(WideStringToString(text))),
			FormatString(L"Content-Type: application/json; charset=UTF-8\r\nOcp-Apim-Subscription-Key:%s", tlp.authKey).c_str()
		})
			if (auto translation = Copy(JSON::Parse(httpRequest.response)[0][L"translations"][0][L"text"].String())) return { true, translation.value() };
			else return { false, FormatString(L"%s: %s", TRANSLATION_ERROR, httpRequest.response) };
		else return { false, FormatString(L"%s (code=%u)", TRANSLATION_ERROR, httpRequest.errorCode) };
	}

	static std::atomic<int> i = 0;
	static Synchronized<std::wstring> token;
	if (token->empty() || isTokenExpired()) if (HttpRequest httpRequest{ L"Mozilla/5.0 Textractor", L"edge.microsoft.com", L"GET", L"/translate/auth" }) // Edge browser: ???
	{
		if (!httpRequest.response.empty()) {
			token->assign(httpRequest.response);
			tokenFetchTime = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
		}
		else {
			return { false, FormatString(L"%s: %s", TRANSLATION_ERROR, BING_TOKEN_RESPONSE_EMPTY) };
		}
	}
	else {
		return { false, FormatString(L"%s: %s", TRANSLATION_ERROR, BING_COULD_NOT_ACQUIRE_TOKEN) };
	}

	std::wstring translateFromComponent = tlp.translateFrom == L"?" ? L"" : L"&from=" + codes.at(tlp.translateFrom);
	if (HttpRequest httpRequest{
		L"Mozilla/5.0 Textractor",
		L"api.cognitive.microsofttranslator.com",
		L"POST",
		FormatString(L"/translate?api-version=3.0&to=%s%s", codes.at(tlp.translateTo), translateFromComponent).c_str(),
		FormatString(R"([{"text":"%s"}])", JSON::Escape(WideStringToString(text))),
		FormatString(L"Content-Type: application/json; charset=UTF-8\r\nAuthorization: Bearer %s", token.Copy()).c_str()
	})
		if (auto translation = Copy(JSON::Parse(httpRequest.response)[0][L"translations"][0][L"text"].String())) return { true, translation.value() };
		else return { false, FormatString(L"%s: %s", TRANSLATION_ERROR, httpRequest.response) };
	else return { false, FormatString(L"%s (code=%u)", TRANSLATION_ERROR, httpRequest.errorCode) };
}
