#include "qtcommon.h"
#include "translatewrapper.h"
#include "network.h"

extern const wchar_t *TRANSLATION_ERROR;

const char *TRANSLATION_PROVIDER = "Google Translate";
const char *GET_API_KEY_FROM = "https://console.cloud.google.com/marketplace/product/google/translate.googleapis.com";
extern const QStringList languagesTo
        {
            "Abkhaz",
            "Acehnese",
            "Acholi",
            "Afrikaans",
            "Albanian",
            "Alur",
            "Amharic",
            "Arabic",
            "Armenian",
            "Assamese",
            "Awadhi",
            "Aymara",
            "Azerbaijani",
            "Balinese",
            "Bambara",
            "Bashkir",
            "Basque",
            "Batak Karo",
            "Batak Simalungun",
            "Batak Toba",
            "Belarusian",
            "Bemba",
            "Bengali",
            "Betawi",
            "Bhojpuri",
            "Bikol",
            "Bosnian",
            "Breton",
            "Bulgarian",
            "Buryat",
            "Cantonese",
            "Catalan",
            "Cebuano",
            "Chichewa",
            "Chinese (Simplified)",
            "Chinese (Traditional)",
            "Chuvash",
            "Corsican",
            "Crimean Tatar",
            "Croatian",
            "Czech",
            "Danish",
            "Dinka",
            "Divehi",
            "Dogri",
            "Dombe",
            "Dutch",
            "Dzongkha",
            "English",
            "Esperanto",
            "Estonian",
            "Ewe",
            "Fijian",
            "Filipino",
            "Finnish",
            "French",
            "French (French)",
            "French (Canadian)",
            "Frisian",
            "Fulfulde",
            "Ga",
            "Galician",
            "Ganda (Luganda)",
            "Georgian",
            "German",
            "Greek",
            "Guarani",
            "Gujarati",
            "Haitian Creole",
            "Hakha Chin",
            "Hausa",
            "Hawaiian",
            "Hebrew",
            "Hiligaynon",
            "Hindi",
            "Hmong",
            "Hungarian",
            "Hunsrik",
            "Icelandic",
            "Igbo",
            "Iloko",
            "Indonesian",
            "Irish",
            "Italian",
            "Japanese",
            "Javanese",
            "Kannada",
            "Kapampangan",
            "Kazakh",
            "Khmer",
            "Kiga",
            "Kinyarwanda",
            "Kituba",
            "Konkani",
            "Korean",
            "Krio",
            "Kurdish (Kurmanji)",
            "Kurdish (Sorani)",
            "Kyrgyz",
            "Lao",
            "Latgalian",
            "Latin",
            "Latvian",
            "Ligurian",
            "Limburgan",
            "Lingala",
            "Lithuanian",
            "Lombard",
            "Luo",
            "Luxembourgish",
            "Macedonian",
            "Maithili",
            "Makassar",
            "Malagasy",
            "Malay",
            "Malay (Jawi)",
            "Malayalam",
            "Maltese",
            "Maori",
            "Marathi",
            "Meadow Mari",
            "Meiteilon (Manipuri)",
            "Minang",
            "Mizo",
            "Mongolian",
            "Myanmar (Burmese)",
            "Ndebele (South)",
            "Nepalbhasa (Newari)",
            "Nepali",
            "Northern Sotho (Sepedi)",
            "Norwegian",
            "Nuer",
            "Occitan",
            "Odia (Oriya)",
            "Oromo",
            "Pangasinan",
            "Papiamento",
            "Pashto",
            "Persian",
            "Polish",
            "Portuguese",
            "Portuguese (Portugal)",
            "Portuguese (Brazil)",
            "Punjabi",
            "Punjabi (Shahmukhi)",
            "Quechua",
            "Romani",
            "Romanian",
            "Rundi",
            "Russian",
            "Samoan",
            "Sango",
            "Sanskrit",
            "Scots Gaelic",
            "Serbian",
            "Sesotho",
            "Seychellois Creole",
            "Shan",
            "Shona",
            "Sicilian",
            "Silesian",
            "Sindhi",
            "Sinhala",
            "Slovak",
            "Slovenian",
            "Somali",
            "Spanish",
            "Sundanese",
            "Swahili",
            "Swati",
            "Swedish",
            "Tajik",
            "Tamil",
            "Tatar",
            "Telugu",
            "Tetum",
            "Thai",
            "Tigrinya",
            "Tsonga",
            "Tswana",
            "Turkish",
            "Turkmen",
            "Twi (Akan)",
            "Ukrainian",
            "Urdu",
            "Uyghur",
            "Uzbek",
            "Vietnamese",
            "Welsh",
            "Xhosa",
            "Yiddish",
            "Yoruba",
            "Yucatec Maya",
            "Zulu",
        }, languagesFrom = languagesTo;
extern const std::unordered_map<std::wstring, std::wstring> codes
{
    {{L"Abkhaz"}, {L"ab"}},
    {{L"Acehnese"}, {L"ace"}},
    {{L"Acholi"}, {L"ach"}},
    {{L"Afrikaans"}, {L"af"}},
    {{L"Albanian"}, {L"sq"}},
    {{L"Alur"}, {L"alz"}},
    {{L"Amharic"}, {L"am"}},
    {{L"Arabic"}, {L"ar"}},
    {{L"Armenian"}, {L"hy"}},
    {{L"Assamese"}, {L"as"}},
    {{L"Awadhi"}, {L"awa"}},
    {{L"Aymara"}, {L"ay"}},
    {{L"Azerbaijani"}, {L"az"}},
    {{L"Balinese"}, {L"ban"}},
    {{L"Bambara"}, {L"bm"}},
    {{L"Bashkir"}, {L"ba"}},
    {{L"Basque"}, {L"eu"}},
    {{L"Batak Karo"}, {L"btx"}},
    {{L"Batak Simalungun"}, {L"bts"}},
    {{L"Batak Toba"}, {L"bbc"}},
    {{L"Belarusian"}, {L"be"}},
    {{L"Bemba"}, {L"bem"}},
    {{L"Bengali"}, {L"bn"}},
    {{L"Betawi"}, {L"bew"}},
    {{L"Bhojpuri"}, {L"bho"}},
    {{L"Bikol"}, {L"bik"}},
    {{L"Bosnian"}, {L"bs"}},
    {{L"Breton"}, {L"br"}},
    {{L"Bulgarian"}, {L"bg"}},
    {{L"Buryat"}, {L"bua"}},
    {{L"Cantonese"}, {L"yue"}},
    {{L"Catalan"}, {L"ca"}},
    {{L"Cebuano"}, {L"ceb"}},
    {{L"Chichewa"}, {L"ny"}},
    {{L"Chinese (Simplified)"}, {L"zh-CN"}},
    {{L"Chinese (Traditional)"}, {L"zh-TW"}},
    {{L"Chuvash"}, {L"cv"}},
    {{L"Corsican"}, {L"co"}},
    {{L"Crimean Tatar"}, {L"crh"}},
    {{L"Croatian"}, {L"hr"}},
    {{L"Czech"}, {L"cs"}},
    {{L"Danish"}, {L"da"}},
    {{L"Dinka"}, {L"din"}},
    {{L"Divehi"}, {L"dv"}},
    {{L"Dogri"}, {L"doi"}},
    {{L"Dombe"}, {L"dov"}},
    {{L"Dutch"}, {L"nl"}},
    {{L"Dzongkha"}, {L"dz"}},
    {{L"English"}, {L"en"}},
    {{L"Esperanto"}, {L"eo"}},
    {{L"Estonian"}, {L"et"}},
    {{L"Ewe"}, {L"ee"}},
    {{L"Fijian"}, {L"fj"}},
    {{L"Filipino"}, {L"tl"}},
    {{L"Finnish"}, {L"fi"}},
    {{L"French"}, {L"fr"}},
    {{L"French (French)"}, {L"fr-FR"}},
    {{L"French (Canadian)"}, {L"fr-CA"}},
    {{L"Frisian"}, {L"fy"}},
    {{L"Fulfulde"}, {L"ff"}},
    {{L"Ga"}, {L"gaa"}},
    {{L"Galician"}, {L"gl"}},
    {{L"Ganda (Luganda)"}, {L"lg"}},
    {{L"Georgian"}, {L"ka"}},
    {{L"German"}, {L"de"}},
    {{L"Greek"}, {L"el"}},
    {{L"Guarani"}, {L"gn"}},
    {{L"Gujarati"}, {L"gu"}},
    {{L"Haitian Creole"}, {L"ht"}},
    {{L"Hakha Chin"}, {L"cnh"}},
    {{L"Hausa"}, {L"ha"}},
    {{L"Hawaiian"}, {L"haw"}},
    {{L"Hebrew"}, {L"iw"}},
    {{L"Hiligaynon"}, {L"hil"}},
    {{L"Hindi"}, {L"hi"}},
    {{L"Hmong"}, {L"hmn"}},
    {{L"Hungarian"}, {L"hu"}},
    {{L"Hunsrik"}, {L"hrx"}},
    {{L"Icelandic"}, {L"is"}},
    {{L"Igbo"}, {L"ig"}},
    {{L"Iloko"}, {L"ilo"}},
    {{L"Indonesian"}, {L"id"}},
    {{L"Irish"}, {L"ga"}},
    {{L"Italian"}, {L"it"}},
    {{L"Japanese"}, {L"ja"}},
    {{L"Javanese"}, {L"jw"}},
    {{L"Kannada"}, {L"kn"}},
    {{L"Kapampangan"}, {L"pam"}},
    {{L"Kazakh"}, {L"kk"}},
    {{L"Khmer"}, {L"km"}},
    {{L"Kiga"}, {L"cgg"}},
    {{L"Kinyarwanda"}, {L"rw"}},
    {{L"Kituba"}, {L"ktu"}},
    {{L"Konkani"}, {L"gom"}},
    {{L"Korean"}, {L"ko"}},
    {{L"Krio"}, {L"kri"}},
    {{L"Kurdish (Kurmanji)"}, {L"ku"}},
    {{L"Kurdish (Sorani)"}, {L"ckb"}},
    {{L"Kyrgyz"}, {L"ky"}},
    {{L"Lao"}, {L"lo"}},
    {{L"Latgalian"}, {L"ltg"}},
    {{L"Latin"}, {L"la"}},
    {{L"Latvian"}, {L"lv"}},
    {{L"Ligurian"}, {L"lij"}},
    {{L"Limburgan"}, {L"li"}},
    {{L"Lingala"}, {L"ln"}},
    {{L"Lithuanian"}, {L"lt"}},
    {{L"Lombard"}, {L"lmo"}},
    {{L"Luo"}, {L"luo"}},
    {{L"Luxembourgish"}, {L"lb"}},
    {{L"Macedonian"}, {L"mk"}},
    {{L"Maithili"}, {L"mai"}},
    {{L"Makassar"}, {L"mak"}},
    {{L"Malagasy"}, {L"mg"}},
    {{L"Malay"}, {L"ms"}},
    {{L"Malay (Jawi)"}, {L"ms-Arab"}},
    {{L"Malayalam"}, {L"ml"}},
    {{L"Maltese"}, {L"mt"}},
    {{L"Maori"}, {L"mi"}},
    {{L"Marathi"}, {L"mr"}},
    {{L"Meadow Mari"}, {L"chm"}},
    {{L"Meiteilon (Manipuri)"}, {L"mni-Mtei"}},
    {{L"Minang"}, {L"min"}},
    {{L"Mizo"}, {L"lus"}},
    {{L"Mongolian"}, {L"mn"}},
    {{L"Myanmar (Burmese)"}, {L"my"}},
    {{L"Ndebele (South)"}, {L"nr"}},
    {{L"Nepalbhasa (Newari)"}, {L"new"}},
    {{L"Nepali"}, {L"ne"}},
    {{L"Northern Sotho (Sepedi)"}, {L"nso"}},
    {{L"Norwegian"}, {L"no"}},
    {{L"Nuer"}, {L"nus"}},
    {{L"Occitan"}, {L"oc"}},
    {{L"Odia (Oriya)"}, {L"or"}},
    {{L"Oromo"}, {L"om"}},
    {{L"Pangasinan"}, {L"pag"}},
    {{L"Papiamento"}, {L"pap"}},
    {{L"Pashto"}, {L"ps"}},
    {{L"Persian"}, {L"fa"}},
    {{L"Polish"}, {L"pl"}},
    {{L"Portuguese"}, {L"pt"}},
    {{L"Portuguese (Portugal)"}, {L"pt-PT"}},
    {{L"Portuguese (Brazil)"}, {L"pt-BR"}},
    {{L"Punjabi"}, {L"pa"}},
    {{L"Punjabi (Shahmukhi)"}, {L"pa-Arab"}},
    {{L"Quechua"}, {L"qu"}},
    {{L"Romani"}, {L"rom"}},
    {{L"Romanian"}, {L"ro"}},
    {{L"Rundi"}, {L"rn"}},
    {{L"Russian"}, {L"ru"}},
    {{L"Samoan"}, {L"sm"}},
    {{L"Sango"}, {L"sg"}},
    {{L"Sanskrit"}, {L"sa"}},
    {{L"Scots Gaelic"}, {L"gd"}},
    {{L"Serbian"}, {L"sr"}},
    {{L"Sesotho"}, {L"st"}},
    {{L"Seychellois Creole"}, {L"crs"}},
    {{L"Shan"}, {L"shn"}},
    {{L"Shona"}, {L"sn"}},
    {{L"Sicilian"}, {L"scn"}},
    {{L"Silesian"}, {L"szl"}},
    {{L"Sindhi"}, {L"sd"}},
    {{L"Sinhala"}, {L"si"}},
    {{L"Slovak"}, {L"sk"}},
    {{L"Slovenian"}, {L"sl"}},
    {{L"Somali"}, {L"so"}},
    {{L"Spanish"}, {L"es"}},
    {{L"Sundanese"}, {L"su"}},
    {{L"Swahili"}, {L"sw"}},
    {{L"Swati"}, {L"ss"}},
    {{L"Swedish"}, {L"sv"}},
    {{L"Tajik"}, {L"tg"}},
    {{L"Tamil"}, {L"ta"}},
    {{L"Tatar"}, {L"tt"}},
    {{L"Telugu"}, {L"te"}},
    {{L"Tetum"}, {L"tet"}},
    {{L"Thai"}, {L"th"}},
    {{L"Tigrinya"}, {L"ti"}},
    {{L"Tsonga"}, {L"ts"}},
    {{L"Tswana"}, {L"tn"}},
    {{L"Turkish"}, {L"tr"}},
    {{L"Turkmen"}, {L"tk"}},
    {{L"Twi (Akan)"}, {L"ak"}},
    {{L"Ukrainian"}, {L"uk"}},
    {{L"Urdu"}, {L"ur"}},
    {{L"Uyghur"}, {L"ug"}},
    {{L"Uzbek"}, {L"uz"}},
    {{L"Vietnamese"}, {L"vi"}},
    {{L"Welsh"}, {L"cy"}},
    {{L"Xhosa"}, {L"xh"}},
    {{L"Yiddish"}, {L"yi"}},
    {{L"Yoruba"}, {L"yo"}},
    {{L"Yucatec Maya"}, {L"yua"}},
    {{L"Zulu"}, {L"zu"}},
    {{L"?"}, {L"auto"}}
};

bool translateSelectedOnly = false, useRateLimiter = true, rateLimitSelected = false, useCache = true, useFilter = true;
int tokenCount = 30, rateLimitTimespan = 60000, maxSentenceSize = 1000;

std::pair<bool, std::wstring> Translate(const std::wstring &text, TranslationParam tlp) {
    try {
        if (!tlp.authKey.empty()) {
            std::wstring translateFromComponent = tlp.translateFrom == L"?"
                                                      ? L""
                                                      : L"&source=" + codes.at(tlp.translateFrom);
            if (HttpRequest httpRequest{
                L"Mozilla/5.0 Textractor",
                L"translation.googleapis.com",
                L"POST",
                FormatString(L"/language/translate/v2?format=text&target=%s&key=%s%s", codes.at(tlp.translateTo),
                             tlp.authKey, translateFromComponent).c_str(),
                FormatString(R"({"q":["%s"]})", JSON::Escape(WideStringToString(text)))
            })
                if (auto translation = Copy(
                    JSON::Parse(httpRequest.response)[L"data"][L"translations"][0][L"translatedText"].String())) return
                        {true, translation.value()};
                else return {false, FormatString(L"%s: %s", TRANSLATION_ERROR, httpRequest.response)};
            else return {false, FormatString(L"%s (code=%u)", TRANSLATION_ERROR, httpRequest.errorCode)};
        }

        std::wstring from = codes.at(tlp.translateFrom), to = codes.at(tlp.translateTo);
        if (HttpRequest httpRequest{
            L"Mozilla/5.0 Textractor",
            L"translate-pa.googleapis.com",
            L"POST",
            L"/v1/translateHtml",
            FormatString(R"([[["%s"],"%s","%s"],"wt_lib"])", JSON::Escape(HTML::Escape(WideStringToString(text))),
                         WideStringToString(from), WideStringToString(to)).c_str(), //还有个te_lib 不知道有没有别的效果
            L"Host: translate-pa.googleapis.com\r\nX-Goog-API-Key: AIzaSyATBXajvzQLTDHEQbcpq0Ihe0vWDHmO520\r\nContent-Type: application/json+protobuf"
        }) {
            if (httpRequest.response.empty()) {
                return {false, L"Empty response from translation API"};
            }
            auto parsedJson = JSON::Parse(httpRequest.response);
            if (!parsedJson.IsArray() || parsedJson.Size() == 0) {
                return {false, L"Invalid JSON response format"};
            }
            auto a = parsedJson[0][0];
            if (!a.IsString()) {
                return {false, L"Unexpected JSON response structure"};
            }

            auto str = HTML::Unescape(JSON::Unescape(*a.String()));
            if (auto translation = Copy(&str))
                return {true, translation.value()};
            return {false, FormatString(L"%s: %s", TRANSLATION_ERROR, httpRequest.response)};
        } else return {false, FormatString(L"%s (code=%u)", TRANSLATION_ERROR, httpRequest.errorCode)};
    } catch (const std::out_of_range &e) {
        return {false, FormatString(L"Key error in translation map: %s", StringToWideString(e.what()).c_str())};
    }
    catch (const std::exception &e) {
        return {false, FormatString(L"Exception occurred: %s", StringToWideString(e.what()).c_str())};
    }
    catch (...) {
        return {false, L"Unknown error occurred during translation"};
    }
}
